export const agenticContent = {
  es: {
    key: 'agentic',
    meta: {
      title: 'Ingeniería de software agéntica: velocidad con control | codiva®',
      description: 'Cómo usar LLMs y agentes de programación para acelerar software con especificaciones, TDD, aislamiento, revisión independiente y gates fail-closed.',
      keywords: 'programación agéntica, ingeniería de software con IA, agentes de programación, LLM desarrollo software, controles para agentes IA',
      canonical: 'https://codiva.cl/conocimiento/ingenieria-software-agentica/',
      ogUrl: 'https://codiva.cl/conocimiento/ingenieria-software-agentica/',
      ogTitle: 'Ingeniería de software agéntica con control — codiva®',
      ogDescription: 'Más capacidad de ejecución exige especificaciones, aislamiento, pruebas y revisión más rigurosos.',
      ogLocale: 'es_CL',
      twitterTitle: 'Programación agéntica con control — codiva®',
      twitterDescription: 'LLMs y agentes bajo TDD, aislamiento, revisión independiente y gates fail-closed.',
    },
    breadcrumb: 'Ingeniería de software agéntica',
    label: 'IA aplicada · Ingeniería de software',
    title: 'La programación agéntica cambia la velocidad, no la responsabilidad',
    lede: 'Un LLM puede proponer código. Un agente puede además leer un repositorio, ejecutar herramientas, modificar archivos y verificar resultados. Eso comprime ciclos de trabajo, pero también aumenta la cantidad de decisiones y cambios que deben controlarse.',
    provenance: 'Método de trabajo de Codiva + arquitectura de referencia. Este enfoque se usa para producir y verificar cambios en este sitio: contrato antes de implementación, ejecución real de pruebas, revisión independiente y publicación solo después de gates verdes. No afirma autonomía total ni resultados garantizados.',
    flowTitle: 'Un ciclo agéntico con límites verificables',
    flowLabel: 'Intención humana, especificación, agentes aislados, pruebas, revisión independiente y despliegue observado',
    flow: [
      { name: 'Intención humana', detail: 'objetivo · restricciones · riesgo' },
      { name: 'Especificación', detail: 'contrato · aceptación · fuera de alcance' },
      { name: 'Agentes aislados', detail: 'contexto mínimo · permisos acotados' },
      { name: 'Evidencia', detail: 'tests · build · análisis · salidas reales' },
      { name: 'Revisión', detail: 'contexto independiente · fail-closed' },
      { name: 'Entrega', detail: 'CI · despliegue · verificación' },
    ],
    sections: [
      {
        control: 'specification',
        title: 'La especificación se vuelve ejecutable',
        text: 'Dar una instrucción vaga a un agente solo produce cambios vagamente correctos a mayor velocidad. Antes de delegar, definimos comportamiento observable, restricciones, evidencia esperada y acciones que requieren autorización humana.',
        bullets: ['Criterios de aceptación que una prueba o inspección pueda comprobar.', 'Límites sobre archivos, sistemas, datos y efectos externos.', 'Fuentes de verdad explícitas; una respuesta plausible no cuenta como evidencia.', 'Parada obligatoria cuando falta contexto o aparece una decisión de negocio.'],
      },
      {
        control: 'tdd',
        title: 'TDD reduce el espacio de error',
        text: 'El ciclo RED–GREEN–REFACTOR le da al agente un objetivo pequeño y falsable. La prueba debe fallar antes del cambio por la razón esperada; luego la implementación mínima la hace pasar y el suite completo detecta regresiones.',
        bullets: ['Una conducta por ciclo, no una pila de tests imaginados.', 'Pruebas sobre HTML, APIs o artefactos reales cuando sea posible.', 'Mutaciones adversariales para comprobar que el contrato no acepta falsos positivos.', 'Refactor solo con el comportamiento en verde.'],
      },
      {
        control: 'sandbox',
        title: 'Aislamiento y permisos por capacidad',
        text: 'Un agente no necesita acceso universal para ser útil. Separamos ramas, contextos y herramientas; damos solo los permisos necesarios para la tarea y exigimos aprobación antes de publicar, borrar, pagar o modificar sistemas externos.',
        bullets: ['Ramas o worktrees aislados para trabajo concurrente.', 'Secretos fuera del prompt, código y logs.', 'Acciones destructivas y publicación detrás de una decisión humana.', 'Resultados de subagentes tratados como reportes hasta verificarlos.'],
      },
      {
        control: 'independent-review',
        title: 'La revisión debe venir de otro contexto',
        text: 'El agente que implementó comparte los mismos supuestos que su solución. Una revisión independiente recibe el contrato y el diff, busca errores de lógica, seguridad y procedencia, y no aprueba porque el autor parezca seguro.',
        bullets: ['Revisor sin la narrativa del implementador.', 'Hallazgos bloqueantes separados de sugerencias.', 'Contenido revisado para no inventar clientes, métricas o capacidades.', 'Correcciones verificadas nuevamente desde cero.'],
      },
      {
        control: 'fail-closed',
        title: 'Los gates fallan de forma segura',
        text: 'Si una prueba no corre, la revisión no puede interpretarse o producción no se puede comprobar, el estado es no verificado. La automatización acelera el camino feliz sin convertir la incertidumbre en una aprobación automática.',
        bullets: ['Build, tipos, seguridad, enlaces, schema y accesibilidad como gates reproducibles.', 'CI verde antes de integrar y desplegar.', 'Verificación HTTP, DOM y visual después de publicar.', 'Rollback o detención cuando la evidencia contradice el cambio.'],
      },
    ],
    buyerTitle: 'Qué decisiones siguen siendo humanas',
    buyerText: 'Las personas conservan el objetivo, las prioridades, el apetito de riesgo, las afirmaciones comerciales, el acceso a datos, los cambios irreversibles y la aceptación final. El agente aumenta la capacidad del equipo; la responsabilidad no se delega.',
    sources: [],
    backLabel: 'Volver a Conocimiento',
    backHref: '/conocimiento/',
  },
  en: {
    key: 'agentic',
    meta: {
      title: 'Agentic software engineering: speed with control | codiva®',
      description: 'How to use LLMs and coding agents to accelerate software with specifications, TDD, isolation, independent review, and fail-closed gates.',
      keywords: 'agentic software engineering, agentic programming, AI coding agents, LLM software development, AI agent controls',
      canonical: 'https://codiva.cl/en/knowledge/agentic-software-engineering/',
      ogUrl: 'https://codiva.cl/en/knowledge/agentic-software-engineering/',
      ogTitle: 'Agentic software engineering with control — codiva®',
      ogDescription: 'More execution capacity requires stronger specifications, isolation, testing, and review.',
      ogLocale: 'en_US',
      twitterTitle: 'Agentic programming with control — codiva®',
      twitterDescription: 'LLMs and agents governed by TDD, isolation, independent review, and fail-closed gates.',
    },
    breadcrumb: 'Agentic software engineering',
    label: 'Applied AI · Software engineering',
    title: 'Agentic programming changes the speed, not the responsibility',
    lede: 'An LLM can propose code. An agent can also read a repository, run tools, modify files, and verify results. That compresses delivery cycles, but it also increases the number of decisions and changes that require control.',
    provenance: 'Codiva working method + reference architecture. This approach is used to produce and verify changes on this site: contract before implementation, real test execution, independent review, and publication only after green gates. It does not claim full autonomy or guaranteed outcomes.',
    flowTitle: 'An agentic cycle with verifiable boundaries',
    flowLabel: 'Human intent, specification, isolated agents, tests, independent review, and observed deployment',
    flow: [
      { name: 'Human intent', detail: 'outcome · constraints · risk' },
      { name: 'Specification', detail: 'contract · acceptance · exclusions' },
      { name: 'Isolated agents', detail: 'minimal context · bounded permissions' },
      { name: 'Evidence', detail: 'tests · build · analysis · real output' },
      { name: 'Review', detail: 'independent context · fail-closed' },
      { name: 'Delivery', detail: 'CI · deployment · verification' },
    ],
    sections: [
      {
        control: 'specification',
        title: 'The specification becomes executable',
        text: 'A vague instruction lets an agent produce vaguely correct changes faster. Before delegation, we define observable behavior, constraints, expected evidence, and actions that require human authorization.',
        bullets: ['Acceptance criteria a test or inspection can verify.', 'Boundaries on files, systems, data, and external effects.', 'Explicit sources of truth; a plausible answer is not evidence.', 'A mandatory stop when context is missing or a business decision appears.'],
      },
      {
        control: 'tdd',
        title: 'TDD reduces the error surface',
        text: 'The RED–GREEN–REFACTOR cycle gives an agent a small, falsifiable target. The test must fail before the change for the expected reason; minimal implementation then makes it pass, and the full suite catches regressions.',
        bullets: ['One behavior per cycle instead of a stack of imagined tests.', 'Tests against real HTML, APIs, or artifacts when possible.', 'Adversarial mutations to prove the contract rejects false positives.', 'Refactoring only while behavior remains green.'],
      },
      {
        control: 'sandbox',
        title: 'Isolation and capability-based permissions',
        text: 'An agent does not need universal access to be useful. We separate branches, contexts, and tools; grant only the permissions needed for the task; and require approval before publishing, deleting, paying, or changing external systems.',
        bullets: ['Isolated branches or worktrees for concurrent work.', 'Secrets kept out of prompts, code, and logs.', 'Destructive actions and publication behind a human decision.', 'Subagent results treated as reports until independently verified.'],
      },
      {
        control: 'independent-review',
        title: 'Review must come from another context',
        text: 'The implementing agent shares assumptions with its solution. An independent reviewer receives the contract and diff, searches for logic, security, and provenance errors, and does not approve merely because the author sounds confident.',
        bullets: ['A reviewer without the implementer’s narrative.', 'Blocking findings separated from suggestions.', 'Content checked against fabricated clients, metrics, or capabilities.', 'Corrections verified again from a clean position.'],
      },
      {
        control: 'fail-closed',
        title: 'Gates fail safely',
        text: 'If a test does not run, review cannot be parsed, or production cannot be checked, the state is unverified. Automation speeds up the happy path without turning uncertainty into automatic approval.',
        bullets: ['Build, types, security, links, schema, and accessibility as reproducible gates.', 'Green CI before integration and deployment.', 'HTTP, DOM, and visual verification after publication.', 'Rollback or stop when evidence contradicts the change.'],
      },
    ],
    buyerTitle: 'Which decisions remain human',
    buyerText: 'People retain the outcome, priorities, risk appetite, commercial claims, data access, irreversible changes, and final acceptance. Agents expand team capacity; responsibility is not delegated.',
    sources: [],
    backLabel: 'Back to Knowledge',
    backHref: '/en/knowledge/',
  },
};
