export const deepseekContent = {
  es: {
    key: 'deepseek-harness',
    meta: {
      title: 'DeepSeek Harness y Cordis: agentes componibles con control | codiva®',
      description: 'Qué es DeepSeek Harness, cómo funciona su arquitectura de plugins y cómo se relaciona con Cordis y el paper DeepSeek-R1.',
      keywords: 'DeepSeek Harness, dsh, Cordis, DeepSeek-R1, agentes IA, plugins, agent harness, ingeniería de software agéntica',
      canonical: 'https://codiva.cl/conocimiento/deepseek-harness/',
      ogUrl: 'https://codiva.cl/conocimiento/deepseek-harness/',
      ogTitle: 'DeepSeek Harness y Cordis — codiva®',
      ogDescription: 'Una lectura técnica sobre composición por plugins, perfiles, herramientas, sesiones y control de agentes.',
      ogLocale: 'es_CL',
      twitterTitle: 'DeepSeek Harness y Cordis — codiva®',
      twitterDescription: 'Qué es dsh, qué aporta Cordis y qué no debe confundirse con el paper DeepSeek-R1.',
    },
    breadcrumb: 'DeepSeek Harness y Cordis',
    label: 'IA aplicada · Agent harnesses',
    title: 'DeepSeek Harness: un runtime de agentes donde todo puede componerse',
    lede: 'DeepSeek Harness (dsh) es un harness de agentes de código abierto de DeepSeek AI. Su propuesta central no es solo ejecutar un modelo: es componer modelos, herramientas, sesiones, interfaces y políticas como plugins reemplazables.',
    provenance: 'Lectura técnica basada en el repositorio y la documentación oficial de DeepSeek Harness, el repositorio del paper de Cordis y los papers públicos de DeepSeek. El proyecto se declara en developer preview y advierte que habrá cambios incompatibles.',
    flowTitle: 'La composición que describe el proyecto',
    flowLabel: 'Perfil, bundles, parches, plugins, agente y herramientas',
    flow: [
      { name: 'Perfil', detail: 'composición nombrada de bundles' },
      { name: 'Bundles', detail: 'configuración distribuible y parcheable' },
      { name: 'Plugins', detail: 'servicios · eventos · capacidades' },
      { name: 'Sesión', detail: 'log durable · contexto reconstruible' },
      { name: 'Agente', detail: 'modelo · herramientas · pasos' },
      { name: 'Política', detail: 'sandbox · aprobación · telemetría' },
    ],
    sections: [
      {
        control: 'definition',
        title: 'Qué es y qué no es DeepSeek Harness',
        text: 'dsh es una plataforma de ejecución y composición para agentes, con Web UI, modo headless, perfiles y un ecosistema de plugins. No es el modelo DeepSeek-R1 ni un paper de entrenamiento. Un modelo puede ser un adaptador dentro del harness; el harness organiza el trabajo que ocurre alrededor del modelo.',
        bullets: [
          'El repositorio oficial lo presenta como open source y en developer preview.',
          'Se puede iniciar con `npx @deepseek-ai/dsh web` o desde el código fuente.',
          'El Web UI requiere configurar un proveedor/modelo y seleccionar un workspace.',
          'La compatibilidad no debe darse por estable: el propio proyecto anuncia cambios incompatibles.',
        ],
      },
      {
        control: 'composition',
        title: '“Everything is a plugin” es una frontera arquitectónica',
        text: 'La arquitectura oficial describe Cordis como el framework bajo dsh: los plugins aportan servicios, eventos tipados y efectos reversibles a un contexto compartido. El modelo, el registro de herramientas, el log de sesión y el loop del agente participan de esa composición.',
        bullets: [
          'Un perfil apila bundles en un orden definido.',
          'Los parches pueden reemplazar filas de configuración o insertar nuevas.',
          'Las capacidades se conectan mediante seams: definición de servicio, proveedor y consumidor.',
          'Cambiar un proveedor puede cambiar una capacidad completa sin forkear cada consumidor.',
        ],
      },
      {
        control: 'runtime',
        title: 'El log de sesión es parte del contrato',
        text: 'La documentación de arquitectura trata el log append-only como la fuente del contexto que ve el modelo. Las sesiones, los turnos, los pasos, los mensajes, las llamadas a herramientas y sus resultados deben poder reconstruirse; lo que llega al modelo debe quedar representado en el log.',
        bullets: [
          'Un turno puede contener cero o más pasos del modelo.',
          'Los eventos durables permiten replay, forks, transcripciones y telemetría.',
          'Las herramientas pasan por una tubería de pre-ejecución, ejecución y post-ejecución.',
          'Agregar contexto visible al modelo requiere una representación durable, no solo una variable temporal.',
        ],
      },
      {
        control: 'operations',
        title: 'La velocidad necesita límites operativos',
        text: 'Un harness útil no elimina las decisiones humanas. Las mueve a límites explícitos: workspace, permisos, sandbox, aprobación, secretos, telemetría y publicación. Para ingeniería de software, la ventaja está en cambiar proveedores y capacidades sin perder trazabilidad.',
        bullets: [
          'Configurar el API key y el workspace son pasos explícitos del Web UI.',
          'El agente puede leer, editar, ejecutar, delegar y mantener un plan bajo la política activa.',
          'Las operaciones que requieren aprobación deben seguir detrás de esa política.',
          'En developer preview, cada actualización debe tratarse como un cambio de compatibilidad que requiere verificación.',
        ],
      },
      {
        control: 'papers',
        title: 'El harness y los papers: relacionados, no equivalentes',
        text: 'DeepSeek-R1 estudia cómo incentivar capacidades de razonamiento mediante reinforcement learning y describe patrones emergentes como reflexión, verificación y adaptación de estrategia. Ese trabajo ayuda a entender el modelo; no documenta la arquitectura de dsh. El paper más directamente conectado con el harness es el preprint de Cordis sobre composición espacio-temporal, efectos reversibles y coeffects reactivos.',
        bullets: [
          'R1 responde a una pregunta de entrenamiento y capacidad de razonamiento.',
          'Cordis responde a una pregunta de composición dinámica de componentes.',
          'dsh aplica esa línea arquitectónica a un runtime de agentes y plugins.',
          'No conviene afirmar que el harness garantiza razonamiento, autonomía o resultados de negocio.',
        ],
      },
    ],
    buyerTitle: 'Cuándo estudiar este enfoque',
    buyerText: 'Cuando estás construyendo agentes con herramientas y necesitas cambiar modelos, políticas, sesiones o interfaces sin convertir el loop central en un monolito. La recomendación es empezar con un caso acotado, registrar las decisiones y validar compatibilidad en cada actualización.',
    serviceTitle: 'Aplicar este criterio a una plataforma de agentes',
    serviceText: 'Podemos ayudarte a separar capacidades, políticas, trazabilidad y operación antes de convertir un prototipo de agente en una dependencia crítica.',
    serviceHref: '/servicios/desarrollo-software-b2b/',
    serviceLabel: 'Diseñar una plataforma de software controlable',
    sourcesTitle: 'Fuentes primarias',
    sources: [
      { label: 'DeepSeek Harness — repositorio oficial', href: 'https://github.com/deepseek-ai/deepseek-harness' },
      { label: 'DeepSeek Harness — arquitectura oficial', href: 'https://github.com/deepseek-ai/deepseek-harness/blob/master/docs/architecture.md' },
      { label: 'DeepSeek Harness — guía del Web UI', href: 'https://github.com/deepseek-ai/deepseek-harness/blob/master/docs/user/guide/index.md' },
      { label: 'Cordis — A Programming Paradigm for Spatiotemporal Composability', href: 'https://github.com/cordiverse/paper' },
      { label: 'DeepSeek-R1 — arXiv:2501.12948', href: 'https://arxiv.org/abs/2501.12948' },
      { label: 'DeepSeek-V3 Technical Report — arXiv:2412.19437', href: 'https://arxiv.org/abs/2412.19437' },
    ],
    backLabel: 'Volver a Conocimiento',
    backHref: '/conocimiento/',
  },
  en: {
    key: 'deepseek-harness',
    meta: {
      title: 'DeepSeek Harness and Cordis: composable agents with control | codiva®',
      description: 'What DeepSeek Harness is, how its plugin architecture works, and how it relates to Cordis and the DeepSeek-R1 paper.',
      keywords: 'DeepSeek Harness, dsh, Cordis, DeepSeek-R1, AI agents, plugins, agent harness, agentic software engineering',
      canonical: 'https://codiva.cl/en/knowledge/deepseek-harness/',
      ogUrl: 'https://codiva.cl/en/knowledge/deepseek-harness/',
      ogTitle: 'DeepSeek Harness and Cordis — codiva®',
      ogDescription: 'A technical reading on plugin composition, profiles, tools, sessions, and agent control.',
      ogLocale: 'en_US',
      twitterTitle: 'DeepSeek Harness and Cordis — codiva®',
      twitterDescription: 'What dsh is, what Cordis contributes, and why it is not the DeepSeek-R1 paper.',
    },
    breadcrumb: 'DeepSeek Harness and Cordis',
    label: 'Applied AI · Agent harnesses',
    title: 'DeepSeek Harness: an agent runtime where everything can be composed',
    lede: 'DeepSeek Harness (dsh) is an open-source agent harness from DeepSeek AI. Its central proposal is not merely to run a model: it composes models, tools, sessions, interfaces, and policies as replaceable plugins.',
    provenance: 'Technical reading based on the official DeepSeek Harness repository and documentation, the Cordis paper repository, and DeepSeek’s public papers. The project identifies itself as a developer preview and warns that compatibility-breaking changes are expected.',
    flowTitle: 'The composition described by the project',
    flowLabel: 'Profile, bundles, patches, plugins, agent, and tools',
    flow: [
      { name: 'Profile', detail: 'named bundle composition' },
      { name: 'Bundles', detail: 'distributable, patchable configuration' },
      { name: 'Plugins', detail: 'services · events · capabilities' },
      { name: 'Session', detail: 'durable log · reconstructable context' },
      { name: 'Agent', detail: 'model · tools · steps' },
      { name: 'Policy', detail: 'sandbox · approval · telemetry' },
    ],
    sections: [
      {
        control: 'definition',
        title: 'What DeepSeek Harness is—and is not',
        text: 'dsh is an execution and composition platform for agents, with a Web UI, headless mode, profiles, and a plugin ecosystem. It is not the DeepSeek-R1 model or a training paper. A model can be an adapter inside the harness; the harness organizes the work around the model.',
        bullets: [
          'The official repository presents it as open source and in developer preview.',
          'It can start with `npx @deepseek-ai/dsh web` or from a source checkout.',
          'The Web UI requires configuring a model provider and selecting a workspace.',
          'Compatibility should not be assumed stable: the project explicitly warns about breaking changes.',
        ],
      },
      {
        control: 'composition',
        title: '“Everything is a plugin” is an architectural boundary',
        text: 'The official architecture describes Cordis as the framework under dsh: plugins contribute services, typed events, and reversible effects to a shared context. The model, tool registry, session log, and agent loop all participate in that composition.',
        bullets: [
          'A profile stacks bundles in a defined order.',
          'Patches can replace configuration rows or insert new ones.',
          'Capabilities connect through seams: service definition, provider, and consumer.',
          'Changing a provider can change a full capability without forking every consumer.',
        ],
      },
      {
        control: 'runtime',
        title: 'The session log is part of the contract',
        text: 'The architecture documentation treats the append-only log as the source of the context seen by the model. Sessions, turns, steps, messages, tool calls, and results should be reconstructable; anything that reaches the model should be represented in the log.',
        bullets: [
          'A turn may contain zero or more model steps.',
          'Durable events support replay, forks, transcripts, and telemetry.',
          'Tools pass through pre-execution, execution, and post-execution stages.',
          'Adding model-visible context requires durable representation, not only a temporary variable.',
        ],
      },
      {
        control: 'operations',
        title: 'Speed needs operational boundaries',
        text: 'A useful harness does not remove human decisions. It moves them into explicit boundaries: workspace, permissions, sandbox, approval, secrets, telemetry, and publication. For software engineering, the advantage is changing providers and capabilities without losing traceability.',
        bullets: [
          'Configuring the API key and workspace are explicit Web UI steps.',
          'The agent can read, edit, execute, delegate, and maintain a plan under the active policy.',
          'Operations requiring approval should remain behind that policy.',
          'In developer preview, every update should be treated as a compatibility change that requires verification.',
        ],
      },
      {
        control: 'papers',
        title: 'The harness and the papers: related, not equivalent',
        text: 'DeepSeek-R1 studies how to incentivize reasoning capabilities through reinforcement learning and describes emergent patterns such as reflection, verification, and strategy adaptation. That work helps explain the model; it does not document dsh’s runtime architecture. The paper most directly connected to the harness is the Cordis preprint on spatiotemporal composition, reversible effects, and reactive coeffects.',
        bullets: [
          'R1 addresses a training and reasoning-capability question.',
          'Cordis addresses a dynamic component-composition question.',
          'dsh applies that architectural line to an agent and plugin runtime.',
          'It would be inaccurate to claim that the harness guarantees reasoning, autonomy, or business outcomes.',
        ],
      },
    ],
    buyerTitle: 'When to study this approach',
    buyerText: 'When you are building tool-using agents and need to change models, policies, sessions, or interfaces without turning the central loop into a monolith. Start with a bounded case, record decisions, and validate compatibility on every update.',
    serviceTitle: 'Apply this judgment to an agent platform',
    serviceText: 'We can help separate capabilities, policy, traceability, and operations before an agent prototype becomes a critical dependency.',
    serviceHref: '/en/services/b2b-software-development/',
    serviceLabel: 'Design a controllable software platform',
    sourcesTitle: 'Primary sources',
    sources: [
      { label: 'DeepSeek Harness — official repository', href: 'https://github.com/deepseek-ai/deepseek-harness' },
      { label: 'DeepSeek Harness — official architecture', href: 'https://github.com/deepseek-ai/deepseek-harness/blob/master/docs/architecture.md' },
      { label: 'DeepSeek Harness — Web UI guide', href: 'https://github.com/deepseek-ai/deepseek-harness/blob/master/docs/user/guide/index.md' },
      { label: 'Cordis — A Programming Paradigm for Spatiotemporal Composability', href: 'https://github.com/cordiverse/paper' },
      { label: 'DeepSeek-R1 — arXiv:2501.12948', href: 'https://arxiv.org/abs/2501.12948' },
      { label: 'DeepSeek-V3 Technical Report — arXiv:2412.19437', href: 'https://arxiv.org/abs/2412.19437' },
    ],
    backLabel: 'Back to Knowledge',
    backHref: '/en/knowledge/',
  },
};
