export const hermesContent = {
  es: {
    key: 'hermes-agent',
    meta: {
      title: 'Hermes Agent: arquitectura, capacidades y SOUL.md | codiva®',
      description: 'Guía de Hermes Agent: arquitectura, agent loop, herramientas, memoria, skills, perfiles, automatización, seguridad y creación de agentes con SOUL.md.',
      keywords: 'Hermes Agent, Nous Research, SOUL.md, agentes IA, agent loop, tool calling, skills, memoria, perfiles, MCP, automatización',
      canonical: 'https://codiva.cl/conocimiento/hermes-agent/',
      ogUrl: 'https://codiva.cl/conocimiento/hermes-agent/',
      ogTitle: 'Hermes Agent: arquitectura y construcción de agentes — codiva®',
      ogDescription: 'Cómo se combinan identidad, contexto, memoria, skills, herramientas, modelos y automatización en Hermes.',
      ogLocale: 'es_CL',
      twitterTitle: 'Hermes Agent: arquitectura y SOUL.md — codiva®',
      twitterDescription: 'Una guía técnica para entender y construir agentes Hermes como perfiles completos, no como prompts aislados.',
    },
    breadcrumb: 'Hermes Agent',
    label: 'IA aplicada · Arquitectura de agentes',
    title: 'Hermes Agent: construir un agente es diseñar un sistema, no solo un prompt',
    lede: 'Hermes Agent es un framework open source de Nous Research que ejecuta un mismo núcleo agéntico desde terminal, escritorio, IDE, API y plataformas de mensajería. Su unidad de diseño útil es el perfil: identidad, modelos, herramientas, memoria, skills, seguridad y automatizaciones con ciclos de vida separados.',
    provenance: 'Guía técnica basada en la documentación y el repositorio oficial de Hermes Agent. Las capacidades evolucionan con rapidez; los nombres, conteos y comandos deben verificarse contra la versión instalada y la documentación vigente.',
    flowTitle: 'Flujo de una ejecución Hermes',
    flowLabel: 'Entrada, prompt, proveedor, loop agéntico, herramientas, estado y entrega',
    flow: [
      { name: 'Entrada', detail: 'CLI · gateway · ACP · API · cron' },
      { name: 'Prompt', detail: 'SOUL · contexto · skills · memoria' },
      { name: 'Proveedor', detail: 'modelo · API mode · fallback' },
      { name: 'Agent loop', detail: 'razonar · llamar tools · iterar' },
      { name: 'Ejecución', detail: 'terminal · archivos · web · MCP' },
      { name: 'Estado y salida', detail: 'SQLite · FTS5 · entrega' },
    ],
    sections: [
      {
        control: 'surfaces',
        title: 'Un núcleo, muchas superficies',
        text: 'El núcleo AIAgent sirve a varias entradas: CLI y TUI, aplicación de escritorio, gateway de mensajería, ACP para editores, servidor compatible con OpenAI, batch runner y biblioteca Python. Las diferencias de interfaz viven fuera del loop central; esa separación permite que el mismo agente actúe desde Telegram o un IDE sin duplicar la lógica de ejecución.',
        bullets: [
          'CLI/TUI para trabajo interactivo en terminal.',
          'Desktop y dashboard para sesiones, configuración y operación visual.',
          'Gateway para Telegram, Discord, Slack, WhatsApp y otros adaptadores.',
          'ACP, API y batch para integración con editores, aplicaciones y experimentos.',
        ],
      },
      {
        control: 'architecture',
        title: 'La arquitectura detrás del agent loop',
        text: 'AIAgent ensambla el prompt y los schemas de herramientas, resuelve proveedor y modo de API, realiza una llamada cancelable al modelo y despacha las tool calls. Los resultados vuelven al historial y el ciclo continúa hasta obtener una respuesta final, alcanzar un límite o ser interrumpido.',
        bullets: [
          'Tres modos convergen en un historial interno común: chat completions, Codex Responses y Anthropic Messages.',
          'Las llamadas múltiples a herramientas pueden ejecutarse en paralelo y sus resultados regresan en el orden original.',
          'Retries, proveedores fallback, compresión y persistencia forman parte del loop, no de una capa improvisada.',
          'La alternancia de roles y los pares tool call/result se preservan como invariantes del historial.',
        ],
      },
      {
        control: 'capabilities',
        title: 'Capacidades: herramientas agrupadas por toolsets',
        text: 'Hermes expone herramientas como funciones registradas y las agrupa en toolsets que pueden habilitarse por superficie. El catálogo incluye trabajo sobre web, navegador, sistema operativo, repositorios, documentos, medios y servicios externos; la disponibilidad real depende de configuración, credenciales y backend.',
        bullets: [
          'Web y navegador: búsqueda, extracción, automatización, snapshots y visión.',
          'Ingeniería: terminal, procesos, lectura, escritura, patches, búsqueda, LSP y ejecución Python programática.',
          'Multimodal: visión, generación de imágenes y video, STT y text-to-speech.',
          'Orquestación: todo, clarify, delegation, cron, kanban, goals y background jobs.',
          'Integraciones: MCP, Home Assistant, Spotify, Discord y plugins especializados.',
        ],
      },
      {
        control: 'learning',
        title: 'Memoria, sesiones y skills no son lo mismo',
        text: 'La memoria conserva hechos compactos y estables; USER.md modela al usuario; SQLite y FTS5 permiten persistir y buscar sesiones; las skills almacenan procedimientos que se cargan solo cuando son relevantes. Esa separación mantiene el contexto base pequeño y convierte una solución repetible en capacidad reutilizable.',
        bullets: [
          'MEMORY.md y USER.md entran como snapshots al crear o reconstruir el prompt.',
          'session_search recupera conversaciones guardadas sin tratarlas como memoria permanente.',
          'SKILL.md usa divulgación progresiva: índice compacto, contenido principal y referencias bajo demanda.',
          'El agente puede crear y mejorar skills; un gate opcional permite revisar cada escritura.',
        ],
      },
      {
        control: 'automation',
        title: 'Automatización, delegación y extensibilidad',
        text: 'Hermes puede convertir una conversación en trabajo paralelo o durable. Los subagentes aíslan contexto para tareas concurrentes; execute_code compone varias herramientas desde Python; cron ejecuta trabajos programados; webhooks reaccionan a eventos externos; MCP y plugins agregan capacidades sin modificar el núcleo.',
        bullets: [
          'delegate_task crea workers aislados y devuelve resultados al agente padre.',
          'Cron soporta horarios, skills adjuntas, scripts, workdir y entrega multiplataforma.',
          'Webhooks con HMAC pueden disparar ejecuciones desde GitHub, CI, monitoreo o sistemas propios.',
          'MCP descubre herramientas por stdio o HTTP y las registra junto a las herramientas nativas.',
          'Plugins pueden aportar tools, hooks, proveedores de memoria, context engines y superficies visuales.',
        ],
      },
      {
        control: 'soul',
        title: 'SOUL.md define identidad; AGENTS.md define el proyecto',
        text: 'SOUL.md vive en HERMES_HOME y ocupa la primera posición del system prompt. Debe contener voz, carácter, postura ante incertidumbre y estilo de interacción que aplican en todos los contextos. Las convenciones de un repositorio, comandos, puertos y arquitectura pertenecen a archivos de contexto del proyecto.',
        bullets: [
          'SOUL.md: identidad durable, tono, directitud, límites de estilo y valores operativos.',
          '.hermes.md o AGENTS.md: reglas, arquitectura, comandos y verificación de un proyecto.',
          'Skills: procedimientos reutilizables y conocimiento especializado bajo demanda.',
          'Memory/User: hechos estables sobre entorno, preferencias y persona; no procedimientos largos.',
          '/personality: overlay temporal de sesión, no sustituto de una identidad bien diseñada.',
        ],
      },
      {
        control: 'build-agent',
        title: 'Cómo construir un agente Hermes',
        text: 'La ruta recomendada es crear un perfil aislado, definir su identidad, elegir modelo y herramientas, agregar reglas de proyecto y skills, configurar memoria e integraciones, y probarlo con tareas adversariales antes de habilitar automatizaciones. Un perfil puede luego exportarse o publicarse como distribución versionada.',
        bullets: [
          'Crear: `hermes profile create research-bot` y ejecutar su setup.',
          'Definir identidad en `$HERMES_HOME/SOUL.md` sin mezclar secretos ni rutas temporales.',
          'Seleccionar proveedor/modelo, fallbacks y toolsets con privilegio mínimo.',
          'Agregar AGENTS.md, skills, MCP y cron solo cuando el caso los necesita.',
          'Dogfood, revisar trazas, validar aprobaciones y publicar como distribución Git si se compartirá.',
        ],
      },
      {
        control: 'prompt',
        title: 'El system prompt es una composición con estabilidad deliberada',
        text: 'Hermes ordena el prompt en tiers estables, contextuales y volátiles. SOUL.md, guía de herramientas y skills forman el prefijo estable; reglas del proyecto forman contexto; memoria, perfil de usuario, timestamp y datos de sesión forman el tier volátil. Los overlays por llamada no mutan el prefijo cacheado.',
        bullets: [
          'La estabilidad del prefijo preserva prompt caching y continuidad.',
          'Los context files pasan por escaneo de seguridad y truncación antes de entrar.',
          'Las escrituras de memoria no reescriben silenciosamente un prompt ya congelado.',
          'La compresión resume el centro del historial y conserva mensajes recientes y pares de herramientas.',
        ],
      },
      {
        control: 'security',
        title: 'Poder operativo exige fronteras explícitas',
        text: 'Un agente con terminal, navegador, credenciales y mensajería puede producir efectos reales. Hermes incorpora aprobación de comandos, redacción de secretos, aislamiento por backend, perfiles separados, autorización en gateway, filtrado de entorno para MCP y checkpoints, pero la configuración sigue siendo una decisión de riesgo del operador.',
        bullets: [
          'Usar aprobaciones smart o manual; reservar el modo yolo para entornos deliberadamente desechables.',
          'Guardar secretos en `.env` o stores de autenticación, nunca en SOUL.md, skills o repositorios.',
          'Elegir local, Docker, SSH o backends cloud según el radio de impacto aceptable.',
          'Tratar skills, plugins, MCP servers y distribuciones como código de terceros con privilegios.',
          'Verificar artefactos, CI, despliegue y efectos externos antes de declarar una tarea terminada.',
        ],
      },
    ],
    buyerTitle: 'La decisión de arquitectura',
    buyerText: 'Hermes encaja cuando necesitas un agente operativo que recuerde, use herramientas, se ejecute en varias superficies y pueda automatizar trabajo con trazabilidad. No reemplaza la política de seguridad ni el diseño del proceso: amplifica ambos, para bien o para mal.',
    serviceTitle: 'Diseñar una plataforma agéntica con límites verificables',
    serviceText: 'Codiva puede ayudarte a separar identidad, capacidades, permisos, memoria, automatización y observabilidad antes de conectar un agente a sistemas críticos.',
    serviceHref: '/servicios/desarrollo-software-b2b/',
    serviceLabel: 'Diseñar una plataforma de agentes',
    sourcesTitle: 'Fuentes oficiales',
    sources: [
      { label: 'Hermes Agent — documentación oficial', href: 'https://hermes-agent.nousresearch.com/docs/' },
      { label: 'Hermes Agent — arquitectura', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/architecture' },
      { label: 'Hermes Agent — agent loop', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/agent-loop' },
      { label: 'Hermes Agent — prompt assembly', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/prompt-assembly' },
      { label: 'Hermes Agent — features overview', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/overview' },
      { label: 'Hermes Agent — Personality & SOUL.md', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/personality' },
      { label: 'Hermes Agent — profiles', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/profiles' },
      { label: 'Hermes Agent — tools and toolsets', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/tools' },
      { label: 'Hermes Agent — skills system', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/skills' },
      { label: 'Hermes Agent — repositorio oficial', href: 'https://github.com/NousResearch/hermes-agent' },
    ],
    backLabel: 'Volver a Conocimiento',
    backHref: '/conocimiento/',
  },

  en: {
    key: 'hermes-agent',
    meta: {
      title: 'Hermes Agent: architecture, capabilities, and SOUL.md | codiva®',
      description: 'Hermes Agent guide covering architecture, agent loop, tools, memory, skills, profiles, automation, security, and building agents with SOUL.md.',
      keywords: 'Hermes Agent, Nous Research, SOUL.md, AI agents, agent loop, tool calling, skills, memory, profiles, MCP, automation',
      canonical: 'https://codiva.cl/en/knowledge/hermes-agent/',
      ogUrl: 'https://codiva.cl/en/knowledge/hermes-agent/',
      ogTitle: 'Hermes Agent: architecture and agent construction — codiva®',
      ogDescription: 'How identity, context, memory, skills, tools, models, and automation combine in Hermes.',
      ogLocale: 'en_US',
      twitterTitle: 'Hermes Agent: architecture and SOUL.md — codiva®',
      twitterDescription: 'A technical guide to building Hermes agents as complete profiles rather than isolated prompts.',
    },
    breadcrumb: 'Hermes Agent',
    label: 'Applied AI · Agent architecture',
    title: 'Hermes Agent: building an agent means designing a system, not just a prompt',
    lede: 'Hermes Agent is an open-source framework from Nous Research that runs one agent core across terminal, desktop, IDE, API, and messaging surfaces. Its useful design unit is the profile: identity, models, tools, memory, skills, security, and automation with separate lifecycles.',
    provenance: 'Technical guide based on the official Hermes Agent documentation and repository. Capabilities evolve quickly; names, counts, and commands should be verified against the installed version and current documentation.',
    flowTitle: 'A Hermes execution flow',
    flowLabel: 'Input, prompt, provider, agent loop, tools, state, and delivery',
    flow: [
      { name: 'Input', detail: 'CLI · gateway · ACP · API · cron' },
      { name: 'Prompt', detail: 'SOUL · context · skills · memory' },
      { name: 'Provider', detail: 'model · API mode · fallback' },
      { name: 'Agent loop', detail: 'reason · call tools · iterate' },
      { name: 'Execution', detail: 'terminal · files · web · MCP' },
      { name: 'State & output', detail: 'SQLite · FTS5 · delivery' },
    ],
    sections: [
      {
        control: 'surfaces',
        title: 'One core, many surfaces',
        text: 'The AIAgent core serves several entry points: CLI and TUI, desktop application, messaging gateway, ACP for editors, an OpenAI-compatible server, batch runner, and Python library. Interface differences live outside the central loop, allowing the same agent to act from Telegram or an IDE without duplicating execution logic.',
        bullets: [
          'CLI/TUI for interactive terminal work.',
          'Desktop and dashboard for sessions, configuration, and visual operations.',
          'Gateway for Telegram, Discord, Slack, WhatsApp, and other adapters.',
          'ACP, API, and batch modes for editors, applications, and experiments.',
        ],
      },
      {
        control: 'architecture',
        title: 'The architecture behind the agent loop',
        text: 'AIAgent assembles the prompt and tool schemas, resolves the provider and API mode, makes an interruptible model request, and dispatches tool calls. Results return to history and the cycle continues until a final response, a budget boundary, or an interruption.',
        bullets: [
          'Three modes converge on one internal history: chat completions, Codex Responses, and Anthropic Messages.',
          'Multiple tool calls can execute concurrently while results return in original order.',
          'Retries, fallback providers, compression, and persistence belong to the loop rather than an improvised wrapper.',
          'Role alternation and tool-call/result pairs remain history invariants.',
        ],
      },
      {
        control: 'capabilities',
        title: 'Capabilities: tools organized into toolsets',
        text: 'Hermes exposes tools as registered functions and groups them into toolsets that can be enabled per surface. The catalog covers web, browser, operating system, repositories, documents, media, and external services; actual availability depends on configuration, credentials, and backend.',
        bullets: [
          'Web and browser: search, extraction, automation, snapshots, and vision.',
          'Engineering: terminal, processes, file operations, patches, search, LSP, and programmatic Python execution.',
          'Multimodal: vision, image and video generation, STT, and text-to-speech.',
          'Orchestration: todo, clarify, delegation, cron, kanban, goals, and background jobs.',
          'Integrations: MCP, Home Assistant, Spotify, Discord, and specialized plugins.',
        ],
      },
      {
        control: 'learning',
        title: 'Memory, sessions, and skills are different systems',
        text: 'Memory stores compact stable facts; USER.md models the user; SQLite and FTS5 persist and search sessions; skills contain procedures that load only when relevant. This separation keeps baseline context small and turns a repeatable solution into reusable capability.',
        bullets: [
          'MEMORY.md and USER.md enter as snapshots when the prompt is created or rebuilt.',
          'session_search retrieves stored conversations without treating them as permanent memory.',
          'SKILL.md uses progressive disclosure: compact index, main content, then references on demand.',
          'The agent can create and improve skills; an optional gate can require review for every write.',
        ],
      },
      {
        control: 'automation',
        title: 'Automation, delegation, and extensibility',
        text: 'Hermes can turn a conversation into parallel or durable work. Subagents isolate context for concurrent tasks; execute_code composes several tools from Python; cron runs scheduled jobs; webhooks react to external events; MCP and plugins add capabilities without changing the core.',
        bullets: [
          'delegate_task creates isolated workers and returns their results to the parent agent.',
          'Cron supports schedules, attached skills, scripts, workdir, and multi-platform delivery.',
          'HMAC-authenticated webhooks can trigger runs from GitHub, CI, monitoring, or internal systems.',
          'MCP discovers tools over stdio or HTTP and registers them beside native tools.',
          'Plugins can contribute tools, hooks, memory providers, context engines, and visual surfaces.',
        ],
      },
      {
        control: 'soul',
        title: 'SOUL.md defines identity; AGENTS.md defines the project',
        text: 'SOUL.md lives in HERMES_HOME and occupies the first position in the system prompt. It should contain voice, character, posture toward uncertainty, and interaction style that apply across contexts. Repository conventions, commands, ports, and architecture belong in project context files.',
        bullets: [
          'SOUL.md: durable identity, tone, directness, stylistic boundaries, and operating values.',
          '.hermes.md or AGENTS.md: project rules, architecture, commands, and verification.',
          'Skills: reusable procedures and specialized knowledge loaded on demand.',
          'Memory/User: stable facts about environment, preferences, and person—not long procedures.',
          '/personality: temporary session overlay, not a replacement for a designed identity.',
        ],
      },
      {
        control: 'build-agent',
        title: 'How to build a Hermes agent',
        text: 'The recommended path is to create an isolated profile, define its identity, select model and tools, add project rules and skills, configure memory and integrations, and test with adversarial tasks before enabling automation. A profile can then be exported or published as a versioned distribution.',
        bullets: [
          'Create: `hermes profile create research-bot`, then run its setup.',
          'Define identity in `$HERMES_HOME/SOUL.md` without secrets or temporary paths.',
          'Select provider/model, fallbacks, and least-privilege toolsets.',
          'Add AGENTS.md, skills, MCP, and cron only when the use case earns them.',
          'Dogfood, inspect traces, validate approvals, and publish as a Git distribution if it will be shared.',
        ],
      },
      {
        control: 'prompt',
        title: 'The system prompt is a deliberately stable composition',
        text: 'Hermes orders the prompt into stable, contextual, and volatile tiers. SOUL.md, tool guidance, and skills form the stable prefix; project rules form context; memory, user profile, timestamp, and session data form the volatile tier. Per-call overlays do not mutate the cached prefix.',
        bullets: [
          'Prefix stability preserves prompt caching and continuity.',
          'Context files pass through security scanning and truncation before inclusion.',
          'Memory writes do not silently rewrite an already-frozen prompt.',
          'Compression summarizes the middle of history while preserving recent messages and tool pairs.',
        ],
      },
      {
        control: 'security',
        title: 'Operational power requires explicit boundaries',
        text: 'An agent with terminal, browser, credentials, and messaging can produce real effects. Hermes provides command approval, secret redaction, backend isolation, profile separation, gateway authorization, MCP environment filtering, and checkpoints, but the operator still owns the risk configuration.',
        bullets: [
          'Use smart or manual approvals; reserve yolo mode for deliberately disposable environments.',
          'Keep secrets in `.env` or authentication stores, never in SOUL.md, skills, or repositories.',
          'Choose local, Docker, SSH, or cloud backends according to acceptable blast radius.',
          'Treat skills, plugins, MCP servers, and distributions as privileged third-party code.',
          'Verify artifacts, CI, deployment, and external effects before declaring work complete.',
        ],
      },
    ],
    buyerTitle: 'The architecture decision',
    buyerText: 'Hermes fits when you need an operational agent that remembers, uses tools, runs across surfaces, and automates work with traceability. It does not replace security policy or process design: it amplifies both, for better or worse.',
    serviceTitle: 'Design an agent platform with verifiable boundaries',
    serviceText: 'Codiva can help separate identity, capabilities, permissions, memory, automation, and observability before connecting an agent to critical systems.',
    serviceHref: '/en/services/b2b-software-development/',
    serviceLabel: 'Design an agent platform',
    sourcesTitle: 'Official sources',
    sources: [
      { label: 'Hermes Agent — official documentation', href: 'https://hermes-agent.nousresearch.com/docs/' },
      { label: 'Hermes Agent — architecture', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/architecture' },
      { label: 'Hermes Agent — agent loop', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/agent-loop' },
      { label: 'Hermes Agent — prompt assembly', href: 'https://hermes-agent.nousresearch.com/docs/developer-guide/prompt-assembly' },
      { label: 'Hermes Agent — features overview', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/overview' },
      { label: 'Hermes Agent — Personality & SOUL.md', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/personality' },
      { label: 'Hermes Agent — profiles', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/profiles' },
      { label: 'Hermes Agent — tools and toolsets', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/tools' },
      { label: 'Hermes Agent — skills system', href: 'https://hermes-agent.nousresearch.com/docs/user-guide/features/skills' },
      { label: 'Hermes Agent — official repository', href: 'https://github.com/NousResearch/hermes-agent' },
    ],
    backLabel: 'Back to Knowledge',
    backHref: '/en/knowledge/',
  },
};
