export const knowledgeContent = {
  es: {
    hub: {
      meta: {
        title: 'Conocimiento sobre software, gestión, datos e IA | codiva®',
        description: 'Guías bilingües de codiva® sobre arquitectura, gestión de software, agentes Hermes, programación agéntica, IoT, PostgreSQL, datos e integraciones.',
        keywords: 'arquitectura de software, Hermes Agent, SOUL.md, agentes IA, patrones de diseño, gestión de proyectos software, programación agéntica, LLM, IoT, PostgreSQL, datos',
        canonical: 'https://codiva.cl/conocimiento/',
        ogUrl: 'https://codiva.cl/conocimiento/',
        ogTitle: 'Conocimiento técnico — codiva®',
        ogDescription: 'Decisiones verificables sobre datos, integraciones, arquitectura e interoperabilidad.',
        ogLocale: 'es_CL',
        twitterTitle: 'Conocimiento técnico — codiva®',
        twitterDescription: 'Datos, integraciones, arquitectura e interoperabilidad sin listas vacías de tecnologías.',
      },
      label: 'Conocimiento',
      title: 'Arquitectura explicada para tomar mejores decisiones',
      intro: 'Guías sobre los límites que importan en producción: fallos, estado, contratos, datos persistentes y recuperación. Son arquitecturas de referencia, no casos de clientes.',
      provenance: 'Arquitectura de referencia',
      read: 'Leer guía',
      articles: [
        {
          href: '/conocimiento/ingesta-iot/',
          area: 'Eventos e IoT',
          title: 'Ingesta IoT que tolera duplicados, desorden y desconexiones',
          summary: 'Listeners, idempotencia, orden por dispositivo, dead-letter, replay y observabilidad sin inventar el protocolo del sistema.',
          topics: ['IoT', 'eventos', 'replay'],
        },
        {
          href: '/conocimiento/nominatim-geocodificacion/',
          area: 'Datos geoespaciales',
          title: 'Nominatim: servicio escalable, datos persistentes',
          summary: 'Una capa de aplicación sin estado alrededor de Nominatim, con PostgreSQL/PostGIS persistente, caché y límites operativos explícitos.',
          topics: ['Nominatim', 'PostGIS', 'Redis'],
        },
        {
          href: '/conocimiento/integraciones-postgresql/',
          area: 'Integraciones y datos',
          title: 'Adaptadores REST/SOAP y PostgreSQL bajo carga',
          summary: 'Contratos, retries, idempotencia y aislamiento del dominio junto a particionamiento, índices, planes de consulta, bloat y autovacuum.',
          topics: ['REST', 'SOAP', 'PostgreSQL'],
        },
        {
          href: '/conocimiento/ingenieria-software-agentica/',
          area: 'IA aplicada e ingeniería',
          title: 'Programación agéntica: más velocidad exige más control',
          summary: 'LLMs y agentes de programación bajo especificaciones, TDD, aislamiento, revisión independiente y gates fail-closed.',
          topics: ['LLM', 'agentes', 'TDD'],
        },
        {
          href: '/conocimiento/hermes-agent/',
          area: 'IA aplicada · Arquitectura',
          title: 'Hermes Agent: arquitectura, capacidades y SOUL.md',
          summary: 'Cómo construir agentes como perfiles completos: identidad, contexto, memoria, skills, herramientas, automatización, seguridad y entrega.',
          topics: ['Hermes', 'SOUL.md', 'agentes'],
        },
        {
          href: '/conocimiento/deepseek-harness/',
          area: 'IA aplicada · Arquitectura',
          title: 'DeepSeek Harness y Cordis: agentes componibles con control',
          summary: 'Qué es dsh, cómo se relaciona con Cordis y por qué DeepSeek-R1 es contexto de modelo, no la arquitectura del harness.',
          topics: ['DeepSeek', 'Cordis', 'plugins'],
        },
        {
          href: '/conocimiento/el-mitico-hombre-mes/',
          area: 'Gestión de software',
          title: 'El mítico hombre-mes: por qué más personas pueden producir más demora',
          summary: 'Una lectura breve sobre plazos, incorporación, comunicación, integridad conceptual y las decisiones que una empresa debe tomar cuando un proyecto se atrasa.',
          topics: ['ley de Brooks', 'equipos', 'plazos'],
          provenanceKind: 'recommended-reading',
          provenance: 'Lectura recomendada',
        },
        {
          href: '/conocimiento/patrones-de-diseno/',
          area: 'Diseño de software',
          title: 'Design Patterns: cómo sigue aplicando hoy',
          summary: 'Una lectura breve sobre Strategy, Adapter, Decorator, Observer y el criterio para usar patrones sin sobrediseñar.',
          topics: ['patrones', 'composición', 'acoplamiento'],
          provenanceKind: 'recommended-reading',
          provenance: 'Lectura recomendada',
        },
      ],
      caseLabel: 'Casos relacionados',
      caseTitle: 'La arquitectura conectada con experiencia real',
      cases: [
        { href: '/proyectos/pipeline-datos/', title: 'Pipeline de datos y enriquecimiento', provenance: 'Experiencia previa + arquitectura de referencia' },
        { href: '/proyectos/interoperabilidad-fhir/', title: 'Interoperabilidad clínica con FHIR', provenance: 'Experiencia previa + arquitectura de referencia' },
      ],
    },
    method: {
      meta: {
        title: 'Cómo trabajamos — Entrega de software con control | codiva®',
        description: 'Proceso comercial breve de codiva®: entender, reducir riesgo, entregar en ciclos cortos y dejar código, documentación y decisiones bajo control del cliente.',
        keywords: 'metodología software, sprints, Scrum, Kanban, demos, retrospectivas, entrega incremental',
        canonical: 'https://codiva.cl/como-construimos/',
        ogUrl: 'https://codiva.cl/como-construimos/',
        ogTitle: 'Cómo trabajamos — codiva®',
        ogDescription: 'Entregables visibles, ciclos cortos, decisiones compartidas y continuidad sin dependencia oculta.',
        ogLocale: 'es_CL',
        twitterTitle: 'Cómo trabajamos — codiva®',
        twitterDescription: 'Un proceso breve para reducir riesgo y entregar software útil por etapas.',
      },
      label: 'Cómo trabajamos',
      title: 'Decisiones visibles. Software útil por etapas.',
      intro: 'No necesitas aprobar una metodología de cien páginas. Necesitas saber qué recibes, cuándo puedes revisarlo y cómo mantenemos bajo control riesgos, presupuesto y continuidad.',
      steps: [
        { number: '01', title: 'Entender el sistema', text: 'Alineamos el problema operativo, usuarios, restricciones, código existente, datos e integraciones. El primer entregable es un mapa compartido, no una promesa abstracta.' },
        { number: '02', title: 'Reducir el riesgo', text: 'Ordenamos decisiones por impacto y reversibilidad. Si el sistema existe, priorizamos estabilidad, observabilidad y una ruta incremental antes de reemplazarlo.' },
        { number: '03', title: 'Entregar y demostrar', text: 'Trabajamos en ciclos de una o dos semanas, con prioridades visibles, demos y criterios de aceptación. En cada demo revisamos software funcionando contigo. Rituales compatibles con Scrum mantienen el ritmo sin convertir el proceso en ceremonia.' },
        { number: '04', title: 'Aprender y continuar', text: 'Las retrospectivas convierten lo aprendido en ajustes concretos. Usamos Kanban para rescate, incidentes y trabajo con prioridad variable.' },
      ],
      controlsTitle: 'Qué permanece bajo tu control',
      controls: [
        'Backlog, alcance y presupuesto visibles.',
        'Riesgos y decisiones importantes comunicados temprano.',
        'Repositorio, infraestructura y propiedad intelectual a tu nombre.',
        'Documentación suficiente para operar, mantener y transferir.',
        'Comunicación directa con Carlos y Marina.',
      ],
      cadenceTitle: 'Cadencia sin teatro',
      cadence: 'Sprints de una o dos semanas (1–2), planificación proporcional, seguimiento breve, demos y retrospectivas. Scrum cuando la cadencia es estable; Kanban cuando incidentes, rescate o dependencias externas cambian la prioridad.',
      knowledgeTitle: 'La profundidad técnica vive en Conocimiento',
      knowledgeText: 'Arquitectura, datos, integraciones, IoT, Nominatim, PostgreSQL y FHIR tienen páginas propias, indexables y enlazables. Esta página queda enfocada en reducir el riesgo del comprador.',
      knowledgeLabel: 'Explorar Conocimiento',
      knowledgeHref: '/conocimiento/',
      ctaTitle: 'Empecemos por el riesgo más importante',
      ctaText: 'Una conversación inicial sirve para decidir si conviene construir, modernizar, rescatar o estudiar primero el sistema.',
      ctaLabel: 'Conversemos sobre tu sistema',
    },
    iot: {
      key: 'iot',
      meta: {
        title: 'Arquitectura de ingesta IoT confiable | codiva®',
        description: 'Arquitectura de referencia para listeners IoT, duplicados, idempotencia, orden, retries, dead-letter, replay y observabilidad.',
        keywords: 'IoT, listeners, ingesta, eventos, idempotencia, dead-letter, replay, observabilidad',
        canonical: 'https://codiva.cl/conocimiento/ingesta-iot/',
        ogUrl: 'https://codiva.cl/conocimiento/ingesta-iot/',
        ogTitle: 'Ingesta IoT confiable — codiva®',
        ogDescription: 'Cómo tolerar duplicados, desorden, desconexiones y reintentos en un flujo de eventos IoT.',
        ogLocale: 'es_CL',
        twitterTitle: 'Ingesta IoT confiable — codiva®',
        twitterDescription: 'Listeners, idempotencia, orden, dead-letter, replay y observabilidad.',
      },
      breadcrumb: 'Ingesta IoT',
      label: 'Arquitectura de referencia · IoT',
      title: 'Ingesta IoT que espera duplicados, desorden y desconexiones',
      lede: 'Un listener que recibe mensajes no es todavía una plataforma de ingesta. La confiabilidad aparece cuando el flujo conserva identidad, tiempo, errores y capacidad de replay.',
      provenance: 'Arquitectura de referencia. Describe patrones que Codiva puede diseñar e implementar. No atribuye protocolos, volúmenes ni resultados a un cliente.',
      flowTitle: 'Flujo de referencia',
      flowLabel: 'Dispositivos, adaptadores, bus, procesamiento y almacenamiento',
      flow: [
        { name: 'Dispositivos', detail: 'identidad · timestamp · secuencia' },
        { name: 'Listeners', detail: 'adaptadores de protocolo' },
        { name: 'Bus', detail: 'particiones · retención · backpressure' },
        { name: 'Procesamiento', detail: 'validación · deduplicación · ventanas' },
        { name: 'Persistencia', detail: 'series · eventos · estado' },
        { name: 'Consumo', detail: 'alertas · APIs · analítica' },
      ],
      sections: [
        { title: 'Semántica antes que tecnología', text: 'Cada evento necesita una identidad estable, origen, tiempo del dispositivo y tiempo de recepción. Sin esos campos, los duplicados y el orden no pueden resolverse de forma defendible.', bullets: ['Idempotencia con claves de evento o secuencia.', 'Orden por dispositivo o partición; no prometer orden global.', 'Ventanas y tolerancia para eventos atrasados.', 'Validación de esquema antes de enriquecer.'] },
        { title: 'Fallos que deben poder recuperarse', text: 'Los retries deben ser acotados. Los eventos agotados pasan a dead-letter con contexto suficiente para diagnóstico y replay; no se descartan ni se reintentan para siempre.', bullets: ['Backpressure cuando la entrada supera el procesamiento.', 'Dead-letter con causa, payload seguro y correlación.', 'Replay controlado sin duplicar efectos.', 'Desconexiones tratadas como comportamiento normal.'] },
        { title: 'Observabilidad operativa', text: 'La observabilidad debe distinguir mensajes recibidos, válidos, duplicados, atrasados, rechazados y pendientes. Una sola métrica de throughput esconde los fallos que importan.', bullets: ['Lag por partición o consumidor.', 'Edad del evento más antiguo pendiente.', 'Tasa de duplicados y rechazos.', 'Alertas sobre SLOs del flujo, no sobre ruido individual.'] },
      ],
      buyerTitle: 'Cuándo usar esta arquitectura',
      buyerText: 'Cuando dispositivos o gateways pueden reconectarse, repetir mensajes, enviar fuera de orden o superar temporalmente la capacidad de procesamiento.',
      sources: [],
      backLabel: 'Volver a Conocimiento',
      backHref: '/conocimiento/',
    },
    nominatim: {
      key: 'nominatim',
      meta: {
        title: 'Nominatim, PostGIS y geocodificación operable | codiva®',
        description: 'Arquitectura Nominatim con capa de aplicación sin estado, PostgreSQL/PostGIS persistente, Redis opcional, caché, límites y observabilidad.',
        keywords: 'Nominatim, geocodificación, PostgreSQL, PostGIS, Redis, arquitectura stateless',
        canonical: 'https://codiva.cl/conocimiento/nominatim-geocodificacion/',
        ogUrl: 'https://codiva.cl/conocimiento/nominatim-geocodificacion/',
        ogTitle: 'Nominatim y geocodificación operable — codiva®',
        ogDescription: 'Escalar la capa HTTP sin olvidar que los datos geoespaciales son persistentes.',
        ogLocale: 'es_CL',
        twitterTitle: 'Nominatim y PostGIS — codiva®',
        twitterDescription: 'Capa de aplicación sin estado, datos persistentes y caché responsable.',
      },
      breadcrumb: 'Nominatim y geocodificación',
      label: 'Arquitectura de referencia · Datos geoespaciales',
      title: 'Nominatim: escalar el servicio sin ocultar el estado',
      lede: 'La capa de aplicación sin estado puede escalar horizontalmente. Nominatim, en cambio, depende de datos persistentes en PostgreSQL/PostGIS y de un proceso explícito de importación y actualización.',
      provenance: 'Arquitectura de referencia. No afirma una instalación concreta, volumen ni resultado de cliente. La topología se adapta a datos, cobertura, frescura y política de uso.',
      flowTitle: 'Separar servicio, caché y datos',
      flowLabel: 'Clientes, gateway, aplicación, caché, Nominatim y datos persistentes',
      flow: [
        { name: 'Clientes', detail: 'búsqueda · reverse geocoding' },
        { name: 'Gateway', detail: 'auth · rate limit · trazas' },
        { name: 'Aplicación', detail: 'sin estado · normalización' },
        { name: 'Redis', detail: 'caché opcional · TTL' },
        { name: 'Nominatim', detail: 'motor de búsqueda geográfica' },
        { name: 'PostgreSQL/PostGIS', detail: 'índices y datos persistentes' },
      ],
      sections: [
        { title: 'Qué puede ser stateless', text: 'El gateway y la capa HTTP pueden evitar sesiones locales y derivar cada respuesta de la solicitud, caché y servicios persistentes. Eso facilita réplicas y despliegues; no convierte el conjunto en un sistema sin estado.', bullets: ['Balanceo entre réplicas de aplicación.', 'Configuración y secretos externos al proceso.', 'Timeouts y cancelación hacia Nominatim.', 'Rate limits por consumidor.'] },
        { title: 'Dónde vive el estado', text: 'PostgreSQL/PostGIS conserva los datos geoespaciales, índices y estructuras que Nominatim consulta. Importaciones, actualizaciones y backups son operaciones stateful que necesitan capacidad, ventanas y recuperación.', bullets: ['Volúmenes persistentes y backup probado.', 'Separación entre importación y consulta.', 'Monitoreo de tamaño, índices y consultas.', 'Política de actualización de datos OpenStreetMap.'] },
        { title: 'Redis es una función, no un trofeo', text: 'Redis puede cachear búsquedas normalizadas, coordinar rate limits o absorber lecturas repetidas. TTL, cardinalidad y estrategia de invalidación deben definirse; si la tasa de acierto no justifica la complejidad, se elimina.', bullets: ['Claves normalizadas y acotadas.', 'TTL según frescura aceptable.', 'Métricas de hit rate y memoria.', 'Fallback correcto ante caída de caché.'] },
      ],
      buyerTitle: 'Cuándo usar esta arquitectura',
      buyerText: 'Cuando necesitas controlar privacidad, cobertura, latencia o costo de geocodificación y puedes operar la base geoespacial persistente que ese control exige.',
      sources: [
        { label: 'Nominatim Administration Guide', href: 'https://nominatim.org/release-docs/latest/admin/Installation/' },
        { label: 'PostGIS Documentation', href: 'https://postgis.net/documentation/' },
      ],
      backLabel: 'Volver a Conocimiento',
      backHref: '/conocimiento/',
    },
    integrations: {
      key: 'integrations-postgresql',
      meta: {
        title: 'Integraciones REST/SOAP y PostgreSQL operable | codiva®',
        description: 'Adaptadores REST y SOAP con contratos, errores e idempotencia; PostgreSQL con particionamiento, índices, planes, bloat y autovacuum.',
        keywords: 'REST, SOAP, adaptadores, PostgreSQL, particionamiento, índices, query plans, bloat, autovacuum',
        canonical: 'https://codiva.cl/conocimiento/integraciones-postgresql/',
        ogUrl: 'https://codiva.cl/conocimiento/integraciones-postgresql/',
        ogTitle: 'Integraciones y PostgreSQL operable — codiva®',
        ogDescription: 'Contratos estables afuera; planes, índices y mantenimiento medidos adentro.',
        ogLocale: 'es_CL',
        twitterTitle: 'REST, SOAP y PostgreSQL — codiva®',
        twitterDescription: 'Adaptadores, idempotencia, query plans, particionamiento, bloat y autovacuum.',
      },
      breadcrumb: 'Integraciones y PostgreSQL',
      label: 'Arquitectura de referencia · Integraciones y datos',
      title: 'Integraciones que sobreviven al cambio',
      lede: 'REST es un estilo arquitectónico. SOAP es un protocolo de mensajería. Ambos pueden integrarse sin contaminar el dominio si contratos, errores y efectos quedan detrás de adaptadores explícitos.',
      provenance: 'Arquitectura de referencia informada por experiencia profesional previa con APIs REST, servicios SOAP, adaptadores, Redis y PostgreSQL. No se atribuyen resultados ni escala a un cliente de Codiva.',
      flowTitle: 'Aislar contratos externos del dominio',
      flowLabel: 'Proveedores, adaptadores, dominio, persistencia y observabilidad',
      flow: [
        { name: 'REST / SOAP', detail: 'auth · contratos · errores' },
        { name: 'Adaptadores', detail: 'mapeo · timeout · retry' },
        { name: 'Dominio', detail: 'reglas sin transporte' },
        { name: 'Outbox', detail: 'atomicidad · idempotencia' },
        { name: 'PostgreSQL', detail: 'tablas · índices · particiones' },
        { name: 'Operación', detail: 'query plans · bloat · autovacuum' },
      ],
      sections: [
        { title: 'Contratos y fallos explícitos', text: 'REST y SOAP no son equivalentes exactos, pero comparten riesgos operativos: autenticación, timeouts, respuestas parciales y cambios de contrato. El adaptador traduce transporte y errores a conceptos del dominio.', bullets: ['Contract tests sobre ejemplos reales.', 'Timeouts y retries solo para operaciones seguras.', 'Idempotency keys o deduplicación para comandos.', 'Circuit breaking cuando protege al sistema, no como decoración.'] },
        { title: 'PostgreSQL: medir antes de partir', text: 'El particionamiento ayuda cuando el patrón de acceso y mantenimiento puede excluir particiones; también agrega objetos y complejidad. Los índices aceleran lecturas a cambio de espacio y costo de escritura. La decisión empieza con datos y un query plan.', bullets: ['EXPLAIN (ANALYZE, BUFFERS) en un entorno seguro.', 'Índices alineados con filtros, joins y orden.', 'Particionamiento por rango, lista o hash solo con un criterio estable.', 'Sharding o distribución únicamente cuando un solo nodo medido deja de ser suficiente.'] },
        { title: 'Bloat y autovacuum son operación normal', text: 'Actualizaciones y borrados dejan tuplas muertas. Autovacuum recupera espacio reutilizable y mantiene estadísticas; su configuración debe observarse por tabla. El bloat se diagnostica con evidencia y conceptos concretos, no con una etiqueta vaga.', bullets: ['Edad de transacciones y riesgo de wraparound.', 'Tuplas muertas, frecuencia y duración de vacuum.', 'Crecimiento de tablas e índices.', 'Reindex o reescritura solo tras medir causa e impacto.'] },
      ],
      buyerTitle: 'Cuándo usar esta arquitectura',
      buyerText: 'Cuando proveedores cambian contratos, los retries pueden duplicar efectos o una base compartida empieza a mostrar latencia y mantenimiento impredecibles.',
      sources: [
        { label: 'PostgreSQL — Table Partitioning', href: 'https://www.postgresql.org/docs/current/ddl-partitioning.html' },
        { label: 'PostgreSQL — Indexes', href: 'https://www.postgresql.org/docs/current/indexes.html' },
        { label: 'PostgreSQL — Using EXPLAIN', href: 'https://www.postgresql.org/docs/current/using-explain.html' },
        { label: 'PostgreSQL — Routine Vacuuming', href: 'https://www.postgresql.org/docs/current/routine-vacuuming.html' },
        { label: 'W3C SOAP Version 1.2', href: 'https://www.w3.org/TR/soap12-part1/' },
      ],
      backLabel: 'Volver a Conocimiento',
      backHref: '/conocimiento/',
    },
  },

  en: {
    hub: {
      meta: {
        title: 'Knowledge on software, management, data, and AI | codiva®',
        description: 'Bilingual codiva® guides on software architecture and management, Hermes agents, agentic programming, IoT, PostgreSQL, data, and integrations.',
        keywords: 'software architecture, Hermes Agent, SOUL.md, AI agents, design patterns, software project management, agentic programming, LLM, IoT, PostgreSQL, data',
        canonical: 'https://codiva.cl/en/knowledge/',
        ogUrl: 'https://codiva.cl/en/knowledge/',
        ogTitle: 'Technical knowledge — codiva®',
        ogDescription: 'Defensible decisions about data, integrations, architecture, and interoperability.',
        ogLocale: 'en_US',
        twitterTitle: 'Technical knowledge — codiva®',
        twitterDescription: 'Data, integrations, architecture, and interoperability without empty technology lists.',
      },
      label: 'Knowledge',
      title: 'Architecture explained for better decisions',
      intro: 'Guides about production boundaries that matter: failure, state, contracts, persistent data, and recovery. These are reference architectures, not client cases.',
      provenance: 'Reference architecture',
      read: 'Read guide',
      articles: [
        { href: '/en/knowledge/iot-ingestion/', area: 'Events and IoT', title: 'IoT ingestion that tolerates duplicates, disorder, and disconnections', summary: 'Listeners, idempotency, per-device ordering, dead-letter, replay, and observability without inventing a system protocol.', topics: ['IoT', 'events', 'replay'] },
        { href: '/en/knowledge/nominatim-geocoding/', area: 'Geospatial data', title: 'Nominatim: scalable service, persistent data', summary: 'A stateless application layer around Nominatim with persistent PostgreSQL/PostGIS, caching, and explicit operational limits.', topics: ['Nominatim', 'PostGIS', 'Redis'] },
        { href: '/en/knowledge/integrations-postgresql/', area: 'Integrations and data', title: 'REST/SOAP adapters and PostgreSQL under load', summary: 'Contracts, retries, idempotency, and domain isolation alongside partitioning, indexes, query plans, bloat, and autovacuum.', topics: ['REST', 'SOAP', 'PostgreSQL'] },
        { href: '/en/knowledge/agentic-software-engineering/', area: 'Applied AI and engineering', title: 'Agentic programming: more speed requires stronger controls', summary: 'LLMs and coding agents governed by specifications, TDD, isolation, independent review, and fail-closed gates.', topics: ['LLM', 'agents', 'TDD'] },
        { href: '/en/knowledge/hermes-agent/', area: 'Applied AI · Architecture', title: 'Hermes Agent: architecture, capabilities, and SOUL.md', summary: 'How to build agents as complete profiles: identity, context, memory, skills, tools, automation, security, and delivery.', topics: ['Hermes', 'SOUL.md', 'agents'] },
        { href: '/en/knowledge/deepseek-harness/', area: 'Applied AI · Architecture', title: 'DeepSeek Harness and Cordis: composable agents with control', summary: 'What dsh is, how it relates to Cordis, and why DeepSeek-R1 is model context rather than the harness architecture.', topics: ['DeepSeek', 'Cordis', 'plugins'] },
        { href: '/en/knowledge/the-mythical-man-month/', area: 'Software management', title: 'The Mythical Man-Month: why more people can create more delay', summary: 'A short reading note on schedules, onboarding, communication, conceptual integrity, and the decisions a company faces when a project runs late.', topics: ["Brooks's Law", 'teams', 'schedules'], provenanceKind: 'recommended-reading', provenance: 'Recommended reading' },
        { href: '/en/knowledge/design-patterns/', area: 'Software design', title: 'Design Patterns: how it still applies today', summary: 'A short reading note on Strategy, Adapter, Decorator, Observer, and the judgment to use patterns without over-designing.', topics: ['patterns', 'composition', 'coupling'], provenanceKind: 'recommended-reading', provenance: 'Recommended reading' },
      ],
      caseLabel: 'Related cases',
      caseTitle: 'Architecture connected to real experience',
      cases: [
        { href: '/en/projects/data-pipeline/', title: 'Data processing and enrichment pipeline', provenance: 'Prior experience + reference architecture' },
        { href: '/en/projects/fhir-interoperability/', title: 'Clinical interoperability with FHIR', provenance: 'Prior experience + reference architecture' },
      ],
    },
    method: {
      meta: {
        title: 'How we work — Software delivery with control | codiva®',
        description: 'Codiva’s concise delivery process: understand, reduce risk, ship in short cycles, and leave code, documentation, and decisions under client control.',
        keywords: 'software methodology, sprints, Scrum, Kanban, demos, retrospectives, incremental delivery',
        canonical: 'https://codiva.cl/en/how-we-build/',
        ogUrl: 'https://codiva.cl/en/how-we-build/',
        ogTitle: 'How we work — codiva®',
        ogDescription: 'Visible deliverables, short cycles, shared decisions, and continuity without hidden dependency.',
        ogLocale: 'en_US',
        twitterTitle: 'How we work — codiva®',
        twitterDescription: 'A concise process to reduce risk and deliver useful software incrementally.',
      },
      label: 'How we work',
      title: 'Visible decisions. Useful software in stages.',
      intro: 'You do not need to approve a hundred-page methodology. You need to know what you receive, when you can review it, and how risk, budget, and continuity stay under control.',
      steps: [
        { number: '01', title: 'Understand the system', text: 'We align on the operational problem, users, constraints, existing code, data, and integrations. The first deliverable is a shared map, not an abstract promise.' },
        { number: '02', title: 'Reduce risk', text: 'We order decisions by impact and reversibility. For an existing system, stability, observability, and an incremental path come before replacement.' },
        { number: '03', title: 'Deliver and demonstrate', text: 'We work in 1–2 week cycles with visible priorities, demos, and acceptance criteria. In every demo we review working software with you. Scrum-compatible rituals keep rhythm without turning delivery into ceremony.' },
        { number: '04', title: 'Learn and continue', text: 'Retrospectives turn learning into concrete adjustments. We use Kanban for rescue, incidents, and variable-priority work.' },
      ],
      controlsTitle: 'What remains under your control',
      controls: ['Visible backlog, scope, and budget.', 'Material risks and decisions communicated early.', 'Repository, infrastructure, and intellectual property in your name.', 'Enough documentation to operate, maintain, and transfer.', 'Direct communication with Carlos and Marina.'],
      cadenceTitle: 'Cadence without theatre',
      cadence: 'One- or two-week iterations (1–2), proportional planning, brief tracking, demos, and retrospectives. Scrum when cadence is stable; Kanban when incidents, rescue work, or external dependencies change priority.',
      knowledgeTitle: 'Technical depth lives in Knowledge',
      knowledgeText: 'Architecture, data, integrations, IoT, Nominatim, PostgreSQL, and FHIR have their own indexable, linkable pages. This page stays focused on reducing buyer risk.',
      knowledgeLabel: 'Explore Knowledge',
      knowledgeHref: '/en/knowledge/',
      ctaTitle: 'Start with the most important risk',
      ctaText: 'An initial conversation can determine whether to build, modernize, rescue, or first study the system.',
      ctaLabel: 'Discuss your system with us',
    },
    iot: {
      key: 'iot',
      meta: {
        title: 'Reliable IoT ingestion architecture | codiva®',
        description: 'Reference architecture for IoT listeners, duplicates, idempotency, ordering, retries, dead-letter, replay, and observability.',
        keywords: 'IoT, listeners, ingestion, events, idempotency, dead-letter, replay, observability',
        canonical: 'https://codiva.cl/en/knowledge/iot-ingestion/', ogUrl: 'https://codiva.cl/en/knowledge/iot-ingestion/', ogTitle: 'Reliable IoT ingestion — codiva®', ogDescription: 'How to tolerate duplicates, disorder, disconnections, and retries in an IoT event flow.', ogLocale: 'en_US', twitterTitle: 'Reliable IoT ingestion — codiva®', twitterDescription: 'Listeners, idempotency, ordering, dead-letter, replay, and observability.',
      },
      breadcrumb: 'IoT ingestion', label: 'Reference architecture · IoT', title: 'IoT ingestion that expects duplicates, disorder, and disconnections', lede: 'A listener receiving messages is not yet an ingestion platform. Reliability appears when the flow preserves identity, time, errors, and replay capability.', provenance: 'Reference architecture. It describes patterns Codiva can design and implement. It does not attribute protocols, volumes, or results to a client.', flowTitle: 'Reference flow', flowLabel: 'Devices, adapters, bus, processing, and storage',
      flow: [{ name: 'Devices', detail: 'identity · timestamp · sequence' }, { name: 'Listeners', detail: 'protocol adapters' }, { name: 'Bus', detail: 'partitions · retention · backpressure' }, { name: 'Processing', detail: 'validation · deduplication · windows' }, { name: 'Persistence', detail: 'series · events · state' }, { name: 'Consumption', detail: 'alerts · APIs · analytics' }],
      sections: [
        { title: 'Semantics before technology', text: 'Each event needs stable identity, source, device time, and receive time. Without those fields, duplicates and ordering cannot be resolved defensibly.', bullets: ['Idempotency through event keys or sequences.', 'Ordering per device or partition; never promise global order.', 'Windows and tolerance for late events.', 'Schema validation before enrichment.'] },
        { title: 'Failures must be recoverable', text: 'Retries must be bounded. Exhausted events move to dead-letter with enough context for diagnosis and replay; they are neither discarded nor retried forever.', bullets: ['Backpressure when input exceeds processing.', 'Dead-letter with cause, safe payload, and correlation.', 'Controlled replay without duplicate effects.', 'Disconnections treated as normal behavior.'] },
        { title: 'Operational observability', text: 'Observability distinguishes received, valid, duplicate, late, rejected, and pending messages. A single throughput metric hides the failures that matter.', bullets: ['Lag by partition or consumer.', 'Age of the oldest pending event.', 'Duplicate and rejection rates.', 'Alerts around flow SLOs, not individual noise.'] },
      ],
      buyerTitle: 'When this architecture fits', buyerText: 'When devices or gateways can reconnect, repeat messages, send out of order, or temporarily exceed processing capacity.', sources: [], backLabel: 'Back to Knowledge', backHref: '/en/knowledge/',
    },
    nominatim: {
      key: 'nominatim',
      meta: {
        title: 'Operable Nominatim and PostGIS geocoding | codiva®', description: 'Nominatim architecture with a stateless application layer, persistent PostgreSQL/PostGIS, optional Redis, caching, limits, and observability.', keywords: 'Nominatim, geocoding, PostgreSQL, PostGIS, Redis, stateless architecture', canonical: 'https://codiva.cl/en/knowledge/nominatim-geocoding/', ogUrl: 'https://codiva.cl/en/knowledge/nominatim-geocoding/', ogTitle: 'Operable Nominatim geocoding — codiva®', ogDescription: 'Scale the HTTP layer without forgetting that geospatial data remains persistent.', ogLocale: 'en_US', twitterTitle: 'Nominatim and PostGIS — codiva®', twitterDescription: 'Stateless application layer, persistent data, and responsible caching.',
      },
      breadcrumb: 'Nominatim geocoding', label: 'Reference architecture · Geospatial data', title: 'Nominatim: scale the service without hiding state', lede: 'A stateless application layer can scale horizontally. Nominatim depends on persistent PostgreSQL/PostGIS data and an explicit import and update process.', provenance: 'Reference architecture. It does not claim a specific installation, volume, or client outcome. The topology must adapt to data, coverage, freshness, and usage policy.', flowTitle: 'Separate service, cache, and data', flowLabel: 'Clients, gateway, application, cache, Nominatim, and persistent data',
      flow: [{ name: 'Clients', detail: 'search · reverse geocoding' }, { name: 'Gateway', detail: 'auth · rate limit · traces' }, { name: 'Application', detail: 'stateless · normalization' }, { name: 'Redis', detail: 'optional cache · TTL' }, { name: 'Nominatim', detail: 'geographic search engine' }, { name: 'PostgreSQL/PostGIS', detail: 'indexes and persistent data' }],
      sections: [
        { title: 'What can be stateless', text: 'The gateway and HTTP application can avoid local sessions and derive every response from the request, cache, and persistent services. That enables replicas and deployment; it does not make the whole system stateless.', bullets: ['Load balancing across application replicas.', 'Configuration and secrets outside the process.', 'Timeout and cancellation toward Nominatim.', 'Rate limits per consumer.'] },
        { title: 'Where state lives', text: 'PostgreSQL/PostGIS stores geospatial data, indexes, and structures queried by Nominatim. Imports, updates, and backups are stateful operations requiring capacity, windows, and recovery.', bullets: ['Persistent volumes and tested backup.', 'Separate import and query workloads.', 'Monitor size, indexes, and queries.', 'OpenStreetMap data update policy.'] },
        { title: 'Redis is a function, not a trophy', text: 'Redis can cache normalized searches, coordinate rate limits, or absorb repeated reads. TTL, cardinality, and invalidation must be defined; remove it if hit rate does not justify complexity.', bullets: ['Normalized, bounded keys.', 'TTL based on acceptable freshness.', 'Hit-rate and memory metrics.', 'Correct fallback when cache is unavailable.'] },
      ],
      buyerTitle: 'When this architecture fits', buyerText: 'When you need control over geocoding privacy, coverage, latency, or cost and can operate the persistent geospatial database that control requires.', sources: [{ label: 'Nominatim Administration Guide', href: 'https://nominatim.org/release-docs/latest/admin/Installation/' }, { label: 'PostGIS Documentation', href: 'https://postgis.net/documentation/' }], backLabel: 'Back to Knowledge', backHref: '/en/knowledge/',
    },
    integrations: {
      key: 'integrations-postgresql',
      meta: {
        title: 'Operable REST/SOAP integrations and PostgreSQL | codiva®', description: 'REST and SOAP adapters with contracts, errors, and idempotency; PostgreSQL with partitioning, indexes, query plans, bloat, and autovacuum.', keywords: 'REST, SOAP, adapters, PostgreSQL, partitioning, indexes, query plans, bloat, autovacuum', canonical: 'https://codiva.cl/en/knowledge/integrations-postgresql/', ogUrl: 'https://codiva.cl/en/knowledge/integrations-postgresql/', ogTitle: 'Operable integrations and PostgreSQL — codiva®', ogDescription: 'Stable contracts outside; measured plans, indexes, and maintenance inside.', ogLocale: 'en_US', twitterTitle: 'REST, SOAP, and PostgreSQL — codiva®', twitterDescription: 'Adapters, idempotency, query plans, partitioning, bloat, and autovacuum.',
      },
      breadcrumb: 'Integrations and PostgreSQL', label: 'Reference architecture · Integrations and data', title: 'Integrations that survive change', lede: 'REST is an architectural style. SOAP is a messaging protocol. Both can be integrated without contaminating the domain when contracts, errors, and effects stay behind explicit adapters.', provenance: 'Reference architecture informed by prior professional experience with REST APIs, SOAP services, adapters, Redis, and PostgreSQL. No outcome or scale is attributed to a Codiva client.', flowTitle: 'Isolate external contracts from the domain', flowLabel: 'Providers, adapters, domain, persistence, and observability',
      flow: [{ name: 'REST / SOAP', detail: 'auth · contracts · errors' }, { name: 'Adapters', detail: 'mapping · timeout · retry' }, { name: 'Domain', detail: 'transport-free rules' }, { name: 'Outbox', detail: 'atomicity · idempotency' }, { name: 'PostgreSQL', detail: 'tables · indexes · partitions' }, { name: 'Operations', detail: 'query plans · bloat · autovacuum' }],
      sections: [
        { title: 'Explicit contracts and failures', text: 'REST and SOAP are not exact equivalents, but share operational risks: authentication, timeouts, partial responses, and contract changes. An adapter translates transport and errors into domain concepts.', bullets: ['Contract tests over real examples.', 'Timeouts and retries only for safe operations.', 'Idempotency keys or deduplication for commands.', 'Circuit breaking only when it protects the system.'] },
        { title: 'PostgreSQL: measure before splitting', text: 'Partitioning helps when access and maintenance patterns can prune partitions; it also adds objects and complexity. Indexes speed reads at the cost of space and writes. Decisions begin with data and a query plan.', bullets: ['EXPLAIN (ANALYZE, BUFFERS) in a safe environment.', 'Indexes aligned with filters, joins, and ordering.', 'Range, list, or hash partitioning only around a stable key.', 'Sharding or distribution only after one measured node is insufficient.'] },
        { title: 'Bloat and autovacuum are normal operations', text: 'Updates and deletes leave dead tuples. Autovacuum recovers reusable space and maintains statistics; its settings must be observed per table. Diagnose bloat with evidence rather than vague fragmentation language.', bullets: ['Transaction age and wraparound risk.', 'Dead tuples, vacuum frequency, and duration.', 'Table and index growth.', 'Reindex or rewrite only after measuring cause and impact.'] },
      ],
      buyerTitle: 'When this architecture fits', buyerText: 'When providers change contracts, retries can duplicate effects, or a shared database starts showing unpredictable latency and maintenance.', sources: [{ label: 'PostgreSQL — Table Partitioning', href: 'https://www.postgresql.org/docs/current/ddl-partitioning.html' }, { label: 'PostgreSQL — Indexes', href: 'https://www.postgresql.org/docs/current/indexes.html' }, { label: 'PostgreSQL — Using EXPLAIN', href: 'https://www.postgresql.org/docs/current/using-explain.html' }, { label: 'PostgreSQL — Routine Vacuuming', href: 'https://www.postgresql.org/docs/current/routine-vacuuming.html' }, { label: 'W3C SOAP Version 1.2', href: 'https://www.w3.org/TR/soap12-part1/' }], backLabel: 'Back to Knowledge', backHref: '/en/knowledge/',
    },
  },
};
