const meta = ({ title, description, keywords, canonical, ogTitle }) => ({
  title,
  description,
  keywords,
  canonical,
  ogUrl: canonical,
  ogTitle,
  ogDescription: description,
  ogLocale: canonical.includes('/en/') ? 'en_US' : 'es_CL',
  twitterTitle: ogTitle,
  twitterDescription: description,
});

export const services = {
  es: {
    b2b: {
      key: 'b2b',
      label: 'Desarrollo de software B2B',
      title: 'Software B2B construido para operaciones complejas',
      intro: 'Diseñamos y construimos productos B2B, plataformas internas y módulos operativos cuando el software debe reflejar reglas reales, integrarse con otros sistemas y quedar bajo control del comprador.',
      promise: 'De la definición del problema a una versión operable, con arquitectura explícita, entregas revisables y transferencia de conocimiento desde el primer ciclo.',
      meta: meta({
        title: 'Desarrollo de software B2B | codiva®',
        description: 'Desarrollo de software B2B crítico, plataformas internas y productos operativos con arquitectura clara, integraciones y trabajo directo de ingenieros senior.',
        keywords: 'desarrollo de software B2B, software empresarial a medida, plataformas internas, productos B2B, ingeniería de software empresarial',
        canonical: 'https://codiva.cl/servicios/desarrollo-software-b2b/',
        ogTitle: 'Desarrollo de software B2B para operaciones complejas — codiva®',
      }),
      problemTitle: 'Cuando una aplicación genérica ya no alcanza',
      problems: [
        'La operación depende de hojas de cálculo, mensajes y pasos manuales que nadie puede auditar de punta a punta.',
        'El producto debe coordinar roles, permisos, estados, aprobaciones y excepciones propias del negocio.',
        'La nueva plataforma necesita convivir con APIs, bases de datos o sistemas existentes sin detener la operación.',
      ],
      deliverablesTitle: 'Qué dejamos en tus manos',
      deliverables: [
        { title: 'Alcance verificable', text: 'Flujos, reglas, criterios de aceptación y decisiones fuera de alcance escritos antes de ampliar el compromiso.' },
        { title: 'Software operable', text: 'Frontend, backend, datos e integraciones desplegados con observabilidad, manejo de errores y documentación útil.' },
        { title: 'Control técnico', text: 'Repositorio, infraestructura, decisiones de arquitectura, pruebas y conocimiento transferidos al comprador.' },
      ],
      approachTitle: 'Cómo reducimos el riesgo',
      approach: [
        { title: 'Entender la operación', text: 'Hablamos con quienes usan y sostienen el proceso. Modelamos estados, invariantes, excepciones y responsabilidades antes de elegir tecnología.' },
        { title: 'Construir una rebanada real', text: 'Validamos un flujo completo de punta a punta en lugar de producir capas desconectadas o una demo sin operación.' },
        { title: 'Entregar en ciclos cortos', text: 'Cada una o dos semanas revisas software funcionando, riesgos abiertos y decisiones. Conservas el control del alcance.' },
      ],
      fitTitle: 'Buen encaje',
      fit: [
        'Producto B2B o plataforma interna con reglas operativas no triviales.',
        'Necesidad de integrar sistemas, datos, permisos y flujos de trabajo.',
        'Equipo comprador disponible para decidir y revisar entregas frecuentes.',
      ],
      notFitTitle: 'No somos el mejor encaje',
      notFit: [
        'Staff augmentation por horas sin responsabilidad sobre un resultado.',
        'Una landing o sitio de marketing sin complejidad de producto.',
        'Un alcance y fecha cerrados antes de entender dependencias y riesgos.',
      ],
      proof: {
        label: 'Producto propio de Codiva',
        title: 'Productos donde producto y operación se encuentran',
        text: 'kit-a, ZooMinder y eConstitucional son productos propios. Demuestran construcción end-to-end, no resultados atribuidos a clientes externos.',
        href: '/proyectos/#codiva-product',
        link: 'Ver productos y procedencia',
      },
      relatedTitle: 'Criterio que puedes inspeccionar',
      related: [
        { title: 'Cómo trabajamos', text: 'Ciclos, control del comprador y evidencia visible.', href: '/como-construimos/' },
        { title: 'Ingeniería de software agéntica', text: 'LLMs y agentes con especificaciones, TDD, aislamiento y revisión independiente.', href: '/conocimiento/ingenieria-software-agentica/' },
        { title: 'Trabajo y arquitecturas', text: 'Productos propios, experiencia previa y referencias separados por procedencia.', href: '/proyectos/' },
      ],
      ctaTitle: 'Conversemos sobre la operación que el software debe sostener',
      ctaText: 'La primera conversación es para entender encaje, restricciones y siguiente paso. Hablas con las personas que construirían el sistema.',
      ctaLabel: 'Conversemos sobre el producto',
      ctaIntent: 'b2b-software-development',
    },
    modernization: {
      key: 'modernization',
      label: 'Modernización de aplicaciones legacy',
      title: 'Moderniza software heredado sin detener la operación',
      intro: 'Estabilizamos y modernizamos sistemas que siguen siendo valiosos, pero se volvieron difíciles de cambiar, desplegar o entender. Primero recuperamos evidencia y control; después elegimos qué conservar, aislar o reemplazar.',
      promise: 'Modernización incremental guiada por riesgo operativo, no una reescritura impulsiva ni una migración de moda.',
      meta: meta({
        title: 'Modernización de aplicaciones legacy | codiva®',
        description: 'Modernización incremental de aplicaciones legacy y sistemas heredados: diagnóstico, estabilidad, observabilidad y evolución sin detener la operación.',
        keywords: 'modernización de aplicaciones legacy, sistemas heredados, modernización de software, migración incremental, estabilización de aplicaciones',
        canonical: 'https://codiva.cl/servicios/modernizacion-aplicaciones-legacy/',
        ogTitle: 'Modernización de aplicaciones legacy con riesgo controlado — codiva®',
      }),
      problemTitle: 'Cuando cambiar el sistema parece más riesgoso que dejarlo quieto',
      problems: [
        'Los despliegues dependen de memoria tribal, pasos manuales o una persona que ya no está.',
        'No hay pruebas ni observabilidad suficientes para distinguir una mejora segura de una regresión.',
        'La plataforma acumula dependencias obsoletas, fallos recurrentes o un modelo de datos que bloquea nuevas capacidades.',
      ],
      deliverablesTitle: 'Qué produce una modernización responsable',
      deliverables: [
        { title: 'Mapa de riesgo', text: 'Arquitectura actual, rutas críticas, dependencias, datos, seguridad, operación y puntos de recuperación documentados.' },
        { title: 'Baseline comprobable', text: 'Build reproducible, pruebas de caracterización, observabilidad y métricas antes de tocar componentes críticos.' },
        { title: 'Ruta incremental', text: 'Secuencia priorizada para estabilizar, encapsular, migrar o retirar piezas con criterios de avance y rollback.' },
      ],
      approachTitle: 'Modernizar sin apostar la empresa',
      approach: [
        { title: 'Recuperar control', text: 'Reproducimos el sistema, examinamos incidentes y trazamos dependencias. Si no podemos observarlo, todavía no prometemos transformarlo.' },
        { title: 'Proteger el comportamiento', text: 'Añadimos contratos y pruebas alrededor de los flujos que no pueden romperse, incluyendo datos, integraciones y trabajos programados.' },
        { title: 'Cambiar por bordes', text: 'Aplicamos separación de módulos, adaptadores, migraciones de datos o reemplazo incremental cuando reducen riesgo de forma demostrable.' },
      ],
      fitTitle: 'Buen encaje',
      fit: [
        'Sistema en producción que conserva valor operativo o datos difíciles de reemplazar.',
        'Software heredado por una adquisición, proveedor anterior o equipo que ya no está.',
        'Necesidad de recuperar velocidad sin detener el negocio para una reescritura total.',
      ],
      notFitTitle: 'No somos el mejor encaje',
      notFit: [
        'Una decisión de reescritura ya cerrada que no admite evidencia contraria.',
        'Un pedido de estimación fija sin acceso al código, datos ni operación.',
        'Ocultar deuda o riesgos a quienes operan y compran el sistema.',
      ],
      proof: {
        label: 'Oferta de entrada',
        title: 'Diagnóstico de rescate de dos semanas',
        text: 'Una revisión acotada para entender el código, priorizar riesgos y entregar un plan con alternativas. El diagnóstico puede recomendar conservar, modernizar o reemplazar.',
        href: '/rescate-de-proyectos/',
        link: 'Ver el diagnóstico de rescate',
      },
      relatedTitle: 'Profundidad relacionada',
      related: [
        { title: 'PostgreSQL e integraciones', text: 'Índices, planes, particionamiento, bloat y autovacuum bajo cargas reales.', href: '/conocimiento/integraciones-postgresql/' },
        { title: 'Ingeniería de software agéntica', text: 'Cómo acelerar cambios sin debilitar pruebas, revisión ni control humano.', href: '/conocimiento/ingenieria-software-agentica/' },
        { title: 'Cómo trabajamos', text: 'Decisiones visibles y ciclos de una o dos semanas.', href: '/como-construimos/' },
      ],
      ctaTitle: 'Empieza por saber qué sistema tienes realmente',
      ctaText: 'Revisamos el contexto y definimos si corresponde una conversación de encaje o un diagnóstico técnico pagado.',
      ctaLabel: 'Conversemos sobre la modernización',
      ctaIntent: 'legacy-application-modernization',
    },
    data: {
      key: 'data',
      label: 'Ingeniería de datos e integraciones',
      title: 'Haz que tus datos operativos sean confiables, conectados y recuperables',
      intro: 'Diseñamos plataformas de datos e integraciones para operaciones donde duplicados, retrasos, contratos incompatibles y fallos parciales son condiciones normales, no excepciones teóricas.',
      promise: 'Pipelines, APIs y flujos de integración con semántica explícita, observabilidad, replay y límites operativos que el equipo puede sostener.',
      meta: meta({
        title: 'Ingeniería de datos e integraciones | codiva®',
        description: 'Ingeniería de datos, pipelines e integraciones complejas con APIs, eventos, observabilidad, recuperación y arquitectura operable.',
        keywords: 'ingeniería de datos, integración de sistemas empresariales, consultoría de datos, integración de APIs, pipelines de datos',
        canonical: 'https://codiva.cl/servicios/ingenieria-datos-integraciones/',
        ogTitle: 'Ingeniería de datos e integraciones operables — codiva®',
      }),
      problemTitle: 'Conectar sistemas no es solo mover campos',
      problems: [
        'Los mismos registros llegan duplicados, fuera de orden o con significado distinto según la fuente.',
        'Una API lenta o caída bloquea procesos internos y no existe una ruta segura de retry o replay.',
        'Los equipos no pueden explicar de dónde vino un dato, qué transformación recibió ni cómo corregirlo.',
      ],
      deliverablesTitle: 'Qué construimos',
      deliverables: [
        { title: 'Contratos explícitos', text: 'Identidad, esquemas, semántica, versionado, idempotencia y ownership definidos en los límites entre sistemas.' },
        { title: 'Flujos recuperables', text: 'Ingesta, validación, deduplicación, reintentos, dead-letter, replay y conciliación diseñados para fallos parciales.' },
        { title: 'Operación observable', text: 'Métricas, trazas, alertas, lineage y runbooks que permiten detectar y resolver problemas sin adivinar.' },
      ],
      approachTitle: 'Arquitectura desde la semántica hasta producción',
      approach: [
        { title: 'Modelar significado y fallos', text: 'Definimos entidades, tiempo, consistencia, volumen, privacidad y modos de fallo antes de elegir batch, eventos o llamadas síncronas.' },
        { title: 'Probar los bordes', text: 'Validamos contratos, duplicados, desorden, timeouts, backpressure y recuperación con casos reproducibles.' },
        { title: 'Diseñar para quien opera', text: 'La plataforma incluye visibilidad, límites y procedimientos de recuperación; no termina cuando el dato llega a una tabla.' },
      ],
      fitTitle: 'Buen encaje',
      fit: [
        'Procesos operativos que dependen de varias fuentes, socios, APIs o eventos.',
        'Datos que deben ser trazables, conciliables y recuperables después de un fallo.',
        'Integraciones donde significado, identidad y consistencia importan más que conectar endpoints.',
      ],
      notFitTitle: 'No somos el mejor encaje',
      notFit: [
        'Un dashboard aislado sin ownership ni calidad de los datos de origen.',
        'Copiar información entre dos herramientas sin requisitos operativos adicionales.',
        'Una arquitectura decidida por una lista de tecnologías antes de entender el flujo.',
      ],
      proof: {
        label: 'Experiencia previa + arquitectura de referencia',
        title: 'De fuentes dispersas a datos confiables',
        text: 'El caso de pipeline explica decisiones, límites y procedencia. No se presenta como un cliente o resultado comercial de Codiva.',
        href: '/proyectos/pipeline-datos/',
        link: 'Ver el caso de ingeniería de datos',
      },
      relatedTitle: 'Arquitecturas que puedes revisar',
      related: [
        { title: 'Ingesta IoT tolerante a fallos', text: 'Duplicados, desorden, desconexiones y backpressure.', href: '/conocimiento/ingesta-iot/' },
        { title: 'PostgreSQL e integraciones', text: 'REST, SOAP y mantenimiento concreto bajo carga.', href: '/conocimiento/integraciones-postgresql/' },
        { title: 'Interoperabilidad FHIR', text: 'Semántica clínica mediante APIs RESTful, mensajería, documentos y otros mecanismos.', href: '/proyectos/interoperabilidad-fhir/' },
      ],
      ctaTitle: 'Conversemos sobre el dato que tu operación necesita confiar',
      ctaText: 'Trae el flujo, los sistemas involucrados y el fallo que más cuesta. Te diremos si somos el equipo adecuado y qué evidencia falta.',
      ctaLabel: 'Revisemos la integración',
      ctaIntent: 'data-engineering-integrations',
    },
  },
  en: {
    b2b: {
      key: 'b2b',
      label: 'B2B software development',
      title: 'Build B2B software that can carry real operations',
      intro: 'We design and build B2B products, internal platforms, and operational modules when software must reflect real business rules, integrate with existing systems, and remain under the buyer’s control.',
      promise: 'From problem definition to an operable release, with explicit architecture, reviewable increments, and knowledge transfer from the first cycle.',
      meta: meta({
        title: 'B2B software development services | codiva®',
        description: 'B2B software development for critical products and internal platforms, with clear architecture, integrations, and direct senior-engineer delivery.',
        keywords: 'B2B software development services, B2B software development company, custom B2B software, internal platforms, enterprise software engineering',
        canonical: 'https://codiva.cl/en/services/b2b-software-development/',
        ogTitle: 'B2B software development for complex operations — codiva®',
      }),
      problemTitle: 'When generic software no longer fits the operation',
      problems: [
        'The business depends on spreadsheets, messages, and manual steps that nobody can audit end to end.',
        'The product must coordinate domain-specific roles, permissions, states, approvals, and exceptions.',
        'A new platform must coexist with existing APIs, databases, or systems without stopping operations.',
      ],
      deliverablesTitle: 'What remains in your hands',
      deliverables: [
        { title: 'Verifiable scope', text: 'Flows, rules, acceptance criteria, and explicit exclusions before the commitment expands.' },
        { title: 'Operable software', text: 'Frontend, backend, data, and integrations deployed with observability, failure handling, and useful documentation.' },
        { title: 'Technical control', text: 'Repository, infrastructure, architecture decisions, tests, and knowledge transferred to the buyer.' },
      ],
      approachTitle: 'How we reduce delivery risk',
      approach: [
        { title: 'Understand the operation', text: 'We work with the people who use and sustain the process. We model states, invariants, exceptions, and ownership before choosing technology.' },
        { title: 'Build a real vertical slice', text: 'We validate one complete workflow rather than producing disconnected layers or a demo that cannot operate.' },
        { title: 'Deliver in short cycles', text: 'Every one or two weeks you review working software, open risks, and decisions. You retain control of scope.' },
      ],
      fitTitle: 'Good fit',
      fit: [
        'A B2B product or internal platform with non-trivial operational rules.',
        'A need to integrate systems, data, permissions, and workflows.',
        'A buyer team available to decide and review frequent increments.',
      ],
      notFitTitle: 'Not the best fit',
      notFit: [
        'Hourly staff augmentation without ownership of an outcome.',
        'A marketing landing page without product complexity.',
        'A fixed scope and date set before dependencies and risks can be examined.',
      ],
      proof: {
        label: 'Codiva-owned products',
        title: 'Products where software meets operations',
        text: 'kit-a, ZooMinder, and eConstitucional are Codiva-owned products. They demonstrate end-to-end building, not outcomes attributed to external clients.',
        href: '/en/projects/#codiva-product',
        link: 'See products and provenance',
      },
      relatedTitle: 'Judgment you can inspect',
      related: [
        { title: 'How we work', text: 'Cycles, buyer control, and visible evidence.', href: '/en/how-we-build/' },
        { title: 'Agentic software engineering', text: 'LLMs and agents governed by specifications, TDD, isolation, and independent review.', href: '/en/knowledge/agentic-software-engineering/' },
        { title: 'Work and architectures', text: 'Owned products, prior experience, and references separated by provenance.', href: '/en/projects/' },
      ],
      ctaTitle: 'Discuss the operation the software must carry',
      ctaText: 'The first conversation is about fit, constraints, and the next useful step. You speak with the people who would build the system.',
      ctaLabel: 'Discuss the product with us',
      ctaIntent: 'b2b-software-development',
    },
    modernization: {
      key: 'modernization',
      label: 'Legacy application modernization',
      title: 'Modernize inherited software without stopping the business',
      intro: 'We stabilize and modernize systems that still carry value but have become difficult to change, deploy, or understand. First we recover evidence and control; then we decide what to preserve, isolate, or replace.',
      promise: 'Incremental modernization driven by operational risk—not an impulsive rewrite or a fashionable migration.',
      meta: meta({
        title: 'Legacy application modernization services | codiva®',
        description: 'Legacy application modernization through assessment, stabilization, observability, and incremental change without stopping business operations.',
        keywords: 'legacy application modernization services, legacy software modernization, inherited systems, incremental modernization, application stabilization',
        canonical: 'https://codiva.cl/en/services/legacy-application-modernization/',
        ogTitle: 'Legacy application modernization with controlled risk — codiva®',
      }),
      problemTitle: 'When changing the system feels riskier than leaving it alone',
      problems: [
        'Deployments depend on tribal knowledge, manual steps, or somebody who is no longer available.',
        'Tests and observability cannot distinguish a safe improvement from a regression.',
        'Obsolete dependencies, recurring incidents, or a constrained data model block new capabilities.',
      ],
      deliverablesTitle: 'What responsible modernization produces',
      deliverables: [
        { title: 'Risk map', text: 'Current architecture, critical paths, dependencies, data, security, operations, and recovery points documented.' },
        { title: 'Evidence baseline', text: 'Reproducible build, characterization tests, observability, and measurements before critical components change.' },
        { title: 'Incremental route', text: 'A prioritized sequence to stabilize, encapsulate, migrate, or retire components with progress and rollback criteria.' },
      ],
      approachTitle: 'Modernize without betting the company',
      approach: [
        { title: 'Recover control', text: 'We reproduce the system, examine incidents, and trace dependencies. If we cannot observe it, we do not promise to transform it yet.' },
        { title: 'Protect behavior', text: 'We add contracts and tests around workflows that cannot break, including data, integrations, and scheduled work.' },
        { title: 'Change at the boundaries', text: 'We use module separation, adapters, data migrations, or incremental replacement when they demonstrably reduce risk.' },
      ],
      fitTitle: 'Good fit',
      fit: [
        'A production system that retains operational value or hard-to-replace data.',
        'Software inherited through an acquisition, previous vendor, or departed team.',
        'A need to regain delivery speed without stopping the business for a total rewrite.',
      ],
      notFitTitle: 'Not the best fit',
      notFit: [
        'A rewrite decision that is closed to contrary evidence.',
        'A fixed estimate requested without access to code, data, or operations.',
        'Hiding debt or risk from the people who buy and operate the system.',
      ],
      proof: {
        label: 'Entry offer',
        title: 'Two-week rescue diagnostic',
        text: 'A bounded review to understand the codebase, prioritize risk, and deliver alternatives. The diagnostic may recommend preserving, modernizing, or replacing parts of the system.',
        href: '/en/project-rescue/',
        link: 'See the rescue diagnostic',
      },
      relatedTitle: 'Related depth',
      related: [
        { title: 'PostgreSQL and integrations', text: 'Indexes, plans, partitioning, bloat, and autovacuum under real workloads.', href: '/en/knowledge/integrations-postgresql/' },
        { title: 'Agentic software engineering', text: 'How to accelerate change without weakening tests, review, or human control.', href: '/en/knowledge/agentic-software-engineering/' },
        { title: 'How we work', text: 'Visible decisions and one- or two-week cycles.', href: '/en/how-we-build/' },
      ],
      ctaTitle: 'Start by learning what system you actually have',
      ctaText: 'We review the context and decide whether the next step is a fit conversation or a paid technical diagnostic.',
      ctaLabel: 'Discuss the modernization',
      ctaIntent: 'legacy-application-modernization',
    },
    data: {
      key: 'data',
      label: 'Data engineering and integrations',
      title: 'Make operational data reliable, connected, and recoverable',
      intro: 'We design data platforms and integrations for operations where duplicates, delays, incompatible contracts, and partial failures are normal conditions—not theoretical exceptions.',
      promise: 'Pipelines, APIs, and integration flows with explicit semantics, observability, replay, and operational limits the team can sustain.',
      meta: meta({
        title: 'Data engineering and integration consulting | codiva®',
        description: 'Data engineering, pipelines, and complex integrations with APIs, events, observability, recovery, and operable architecture.',
        keywords: 'data engineering consulting services, data integration consulting services, data platform consulting, custom API integration, data pipelines',
        canonical: 'https://codiva.cl/en/services/data-engineering-integrations/',
        ogTitle: 'Operable data engineering and integrations — codiva®',
      }),
      problemTitle: 'Connecting systems is not just moving fields',
      problems: [
        'The same records arrive duplicated, out of order, or with different meaning in each source.',
        'A slow or unavailable API blocks internal processes without a safe retry or replay path.',
        'Teams cannot explain where data came from, what transformed it, or how to correct it.',
      ],
      deliverablesTitle: 'What we build',
      deliverables: [
        { title: 'Explicit contracts', text: 'Identity, schemas, semantics, versioning, idempotency, and ownership defined at system boundaries.' },
        { title: 'Recoverable flows', text: 'Ingestion, validation, deduplication, retries, dead letters, replay, and reconciliation designed for partial failure.' },
        { title: 'Observable operations', text: 'Metrics, traces, alerts, lineage, and runbooks that let teams detect and resolve problems without guessing.' },
      ],
      approachTitle: 'Architecture from semantics to production',
      approach: [
        { title: 'Model meaning and failure', text: 'We define entities, time, consistency, volume, privacy, and failure modes before choosing batch, events, or synchronous calls.' },
        { title: 'Test the boundaries', text: 'We validate contracts, duplicates, disorder, timeouts, backpressure, and recovery with reproducible cases.' },
        { title: 'Design for the operator', text: 'The platform includes visibility, limits, and recovery procedures; it does not end when data reaches a table.' },
      ],
      fitTitle: 'Good fit',
      fit: [
        'Operational processes that depend on multiple sources, partners, APIs, or events.',
        'Data that must be traceable, reconcilable, and recoverable after failure.',
        'Integrations where meaning, identity, and consistency matter more than connecting endpoints.',
      ],
      notFitTitle: 'Not the best fit',
      notFit: [
        'An isolated dashboard with no ownership or quality work at the source.',
        'Copying information between two tools without additional operational requirements.',
        'An architecture chosen from a technology list before understanding the flow.',
      ],
      proof: {
        label: 'Prior experience + reference architecture',
        title: 'From scattered sources to trusted data',
        text: 'The pipeline case explains decisions, limits, and provenance. It is not presented as a Codiva client or commercial outcome.',
        href: '/en/projects/data-pipeline/',
        link: 'See the data engineering case',
      },
      relatedTitle: 'Architectures you can inspect',
      related: [
        { title: 'Failure-tolerant IoT ingestion', text: 'Duplicates, disorder, disconnections, and backpressure.', href: '/en/knowledge/iot-ingestion/' },
        { title: 'PostgreSQL and integrations', text: 'REST, SOAP, and concrete maintenance under load.', href: '/en/knowledge/integrations-postgresql/' },
        { title: 'FHIR interoperability', text: 'Clinical semantics through RESTful APIs, messaging, documents, and other mechanisms.', href: '/en/projects/fhir-interoperability/' },
      ],
      ctaTitle: 'Discuss the data your operation needs to trust',
      ctaText: 'Bring the flow, systems, and most expensive failure. We will tell you whether we are the right team and what evidence is missing.',
      ctaLabel: 'Review the integration with us',
      ctaIntent: 'data-engineering-integrations',
    },
  },
};

export function serviceSchema(content, homeUrl, homeLabel) {
  return [
    {
      '@context': 'https://schema.org',
      '@type': 'Service',
      name: content.label,
      serviceType: content.label,
      description: content.meta.description,
      url: content.meta.canonical,
      provider: { '@type': 'Organization', name: 'codiva', url: 'https://codiva.cl' },
    },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: homeLabel, item: homeUrl },
        { '@type': 'ListItem', position: 2, name: content.label, item: content.meta.canonical },
      ],
    },
  ];
}
